# Generated by Django 2.2.2 on 2019-10-05 03:25

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('-1', 'cancelled'), ('0', 'pending'), ('1', 'paid')], default='0', max_length=2)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('currency', models.CharField(blank=True, default='USD', max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('currency', models.CharField(blank=True, default='USD', max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('refund_type', models.CharField(choices=[('1', 'cancel_shipping')], default='1', max_length=2)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('currency', models.CharField(blank=True, default='USD', max_length=30)),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'settled')], default='0', max_length=2)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=11)),
                ('type', models.CharField(choices=[('0', 'refund'), ('1', 'charge')], db_index=True, max_length=2)),
                ('status', models.CharField(choices=[('0', 'failed'), ('1', 'success')], db_index=True, max_length=2)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField()),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-create_time', '-id'],
            },
        ),
    ]
