# Generated by Django 2.2.2 on 2019-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0002_auto_20191005_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('2', 'stripe'), ('1', 'braintree')], db_index=True, default=1, max_length=2),
            preserve_default=False,
        ),
    ]
