# Generated by Django 2.2.2 on 2019-10-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0003_transaction_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicepack',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
