# Generated by Django 2.2 on 2019-10-24 17:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0004_auto_20191024_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='billing_inv_tsv_met_453809_gin'),
        ),
    ]
