# Generated by Django 2.2.2 on 2019-10-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0006_create_text_search_trigger_20191024_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
