# Generated by Django 2.2.2 on 2019-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0007_auto_20191026_1548'),
    ]

    operations = [
        migrations.RunSQL('alter table billing_invoiceitem alter column order_item_id type bigint using order_item_id::bigint;')
    ]
