# Generated by Django 2.2 on 2019-10-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0008_update_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='billing.Invoice'),
        ),
    ]
