# Generated by Django 2.2 on 2020-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0009_auto_20191030_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
