# Generated by Django 2.2 on 2020-02-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0011_update_text_search_trigger_20201015_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepack',
            name='status',
            field=models.CharField(choices=[('-1', 'cancelled'), ('0', 'pending'), ('1', 'paid'), ('2', 'refunded')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('-1', 'cancelled'), ('0', 'pending'), ('1', 'paid'), ('2', 'refunded')], default='0', max_length=2),
        ),
    ]
