# Generated by Django 2.2.2 on 2020-02-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0013_auto_20200207_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('-1', 'canceled'), ('0', 'pending'), ('1', 'paid')], default='0', max_length=2),
        ),
    ]
