# Generated by Django 2.2.2 on 2020-02-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0014_auto_20200207_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('2', 'stripe'), ('1', 'braintree'), ('3', 'payoneer')], db_index=True, max_length=2),
        ),
    ]
