# Generated by Django 2.2.2 on 2020-02-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0015_auto_20200210_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('-1', 'canceled'), ('0', 'pending'), ('1', 'paid'), ('2', 'failed')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='invoicepack',
            name='status',
            field=models.CharField(choices=[('-1', 'canceled'), ('0', 'pending'), ('1', 'paid'), ('2', 'refunded'), ('3', 'failed')], default='0', max_length=2),
        ),
    ]
