# Generated by Django 2.2.2 on 2020-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0016_auto_20200210_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepack',
            name='status',
            field=models.CharField(choices=[('-1', 'canceled'), ('0', 'pending'), ('1', 'paid'), ('2', 'failed'), ('3', 'refunded')], default='0', max_length=2),
        ),
    ]
