# Generated by Django 2.2.2 on 2020-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0018_update_related_order_financial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'settled'), ('2', 'failed')], default='0', max_length=2),
        ),
    ]
