# Generated by Django 2.2.2 on 2020-02-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0021_alter_invoice_id_set_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('2', 'stripe'), ('1', 'braintree'), ('3', 'payoneer'), ('4', 'paypal_pro')], db_index=True, max_length=2),
        ),
    ]
