# Generated by Django 2.2.2 on 2020-02-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0022_auto_20200221_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('-1', 'canceled'), ('0', 'pending'), ('1', 'paid'), ('2', 'failed')], db_index=True, default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='invoicepack',
            name='status',
            field=models.CharField(choices=[('-1', 'canceled'), ('0', 'pending'), ('1', 'paid'), ('2', 'failed'), ('3', 'refunded')], db_index=True, default='0', max_length=2),
        ),
    ]
