# Generated by Django 2.2.2 on 2020-04-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_auto_20200227_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
