# Generated by Django 2.2.2 on 2020-04-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_auto_20200421_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(choices=[('2', 'stripe'), ('1', 'braintree'), ('3', 'payoneer'), ('4', 'paypal_pro'), ('5', 'paypal_vault')], db_index=True, max_length=2),
        ),
    ]
