# Generated by Django 2.2.2 on 2020-05-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_auto_20200430_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='charge_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('-1', 'canceled'), ('0', 'pending'), ('1', 'paid'), ('2', 'failed'), ('4', 'processing'), ('3', 'pending'), ('5', 'transaction_pending')], db_index=True, default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('0', 'failed'), ('1', 'success'), ('2', 'transaction_failed'), ('3', 'transaction_pending')], db_index=True, max_length=2),
        ),
    ]
