# Generated by Django 2.2.2 on 2020-07-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_auto_20200531_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicepack',
            old_name='subtotal',
            new_name='production_cost',
        ),
    ]
