# Generated by Django 2.2.2 on 2020-07-29 07:44

import billing.models.refund
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_auto_20200728_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=billing.models.refund.default_refund_info),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('1', 'cancel_shipping'), ('2', 'reject_order_items')], default='1', max_length=2),
        ),
    ]
