# Generated by Django 2.2.2 on 2020-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_auto_20200729_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('-1', 'canceled'), ('0', 'unpaid'), ('1', 'paid'), ('2', 'failed'), ('4', 'processing'), ('3', 'pending'), ('5', 'transaction_pending')], db_index=True, default='0', max_length=2),
        ),
    ]
