# Generated by Django 2.2.2 on 2020-10-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_auto_20200828_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('0', 'failed'), ('1', 'success'), ('2', 'transaction_failed'), ('3', 'transaction_pending'), ('4', 'canceled')], db_index=True, max_length=2),
        ),
    ]
