# Generated by Django 2.2.2 on 2020-10-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_auto_20201005_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway_transaction_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
