# Generated by Django 2.2.2 on 2020-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_transaction_payment_gateway_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
