# Generated by Django 2.2.2 on 2020-11-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_auto_20201023_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepack',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
