# Generated by Django 2.2.2 on 2020-11-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_migrate_old_refund_data_to_correct_refund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='approve_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'settled'), ('2', 'failed'), ('3', 'rejected'), ('4', 'in_review')], default='4', max_length=2),
        ),
    ]
