# Generated by Django 2.2.2 on 2020-12-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_auto_20201127_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('1', 'cancel_shipping'), ('2', 'reject_order_items'), ('2', 'pay_back_manually')], default='1', max_length=2),
        ),
    ]
