# Generated by Django 2.2.2 on 2020-12-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_auto_20201207_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('1', 'cancel_shipping'), ('2', 'reject_order_items'), ('3', 'pay_back_manually')], default='1', max_length=2),
        ),
    ]
