# Generated by Django 2.2.2 on 2020-12-08 16:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_auto_20201208_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='billing_tra_tsv_met_48f7a9_gin'),
        ),
    ]
