# Generated by Django 2.2.2 on 2020-12-10 09:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0041_update_text_search_trigger_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='billing_ref_tsv_met_218339_gin'),
        ),
    ]
