# Generated by Django 2.2.2 on 2020-12-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0047_update_text_search_trigger_transaction_004'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
