version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5682:5672"
      - "15682:15672"
      - "15681:15671"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbit:/var/lib/rabbitmq
    networks:
      - ffh-net

  db:
    image: "postgres:11"
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fulfill000
      - POSTGRES_DB=fulfillment-hub
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - ffh-net

  web:
    build:
      context: ./
      dockerfile: Dockerfile.Web
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - ffh-net

  payment_processor:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.PaymentProcessor
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbit
      - celery-beat
    env_file:
      - ./.env
    networks:
      - ffh-net

  celery-worker:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.CeleryWorker
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbit
      - celery-beat
    env_file:
      - ./.env
    networks:
      - ffh-net

  celery-beat:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.CeleryBeat
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbit
    env_file:
      - ./.env
    networks:
      - ffh-net

  redis:
    restart: always
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6389:6379"
    volumes:
      - ./redisdata:/var/lib/redis
    networks:
      - ffh-net

networks:
  ffh-net:
    driver: bridge
