# Generated by Django 2.2.2 on 2020-11-18 02:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0093_auto_20201103_0820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('1', 'monetary_cut_down_by_value'), ('2', 'monetary_cut_down_to_value'), ('3', 'percentage_cut_down_by_value')], max_length=20)),
                ('value', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('redeeming_limit', models.PositiveIntegerField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('extra_constraints', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coupon',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CouponCampaign',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coupon_campaign',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RedeemedCouponTransaction',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=50, unique=True)),
                ('redeemed_detail', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('redeemed_time', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='coupon.Coupon')),
                ('order_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='order.OrderPack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_redeemed_coupon_transaction',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupon.CouponCampaign'),
        ),
    ]
