# Generated by Django 2.2.2 on 2020-11-18 15:48

from django.db import migrations

from HUB.models.random_id_model import RandomIDModel
from coupon.models import CouponCampaign, Coupon, RedeemedCouponTransaction


def random_id_coupon_app(apps, schema_editor):
    RandomIDModel.init_random_seq(CouponCampaign)
    RandomIDModel.init_random_seq(Coupon)
    RandomIDModel.init_random_seq(RedeemedCouponTransaction)


class Migration(migrations.Migration):
    dependencies = [
        ('coupon', '0002_auto_20201118_0230'),
    ]

    operations = [
        migrations.RunPython(random_id_coupon_app),
    ]
