# Generated by Django 2.2.2 on 2020-11-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_random_id_coupon_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcampaign',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
