# Generated by Django 2.2.2 on 2020-11-19 01:24

from django.db import migrations, models
import django.db.models.deletion

from order.models import Order


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0093_auto_20201103_0820'),
        ('coupon', '0004_auto_20201118_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemedcoupontransaction',
            name='order_pack',
        ),
        migrations.AddField(
            model_name='redeemedcoupontransaction',
            name='order',
            field=models.ForeignKey(default=Order.objects.only("id", "customer_info", "shipping_rate").first().id,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='applied_coupons', to='order.Order'),
            preserve_default=False,
        ),
    ]
