# Generated by Django 2.2.2 on 2020-11-19 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_auto_20201119_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemedcoupontransaction',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_coupon_transactions', to='coupon.Coupon'),
        ),
        migrations.AlterField(
            model_name='redeemedcoupontransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_coupon_transactions', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='redeemedcoupontransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_coupon_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
