# Generated by Django 2.2.2 on 2020-11-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_auto_20201119_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemedcoupontransaction',
            name='idempotency_key',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
