# Generated by Django 2.2.2 on 2020-11-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_auto_20201119_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='constraint_validating_type',
            field=models.CharField(blank=True, choices=[('0', 'unknown'), ('1', 'order_with_one_item_one_quantity')], default='0', max_length=20),
        ),
    ]
