# Generated by Django 2.2.2 on 2020-11-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0093_auto_20201103_0820'),
        ('coupon', '0008_coupon_constraint_validating_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='orders',
            field=models.ManyToManyField(related_name='applied_coupons', through='coupon.RedeemedCouponTransaction', to='order.Order'),
        ),
    ]
