# Generated by Django 2.2.2 on 2020-11-20 09:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_coupon_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='value_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'production_cost': {'discount_value': 0, 'max_discount_in_usd': -1, 'min_cost_in_usd': 0}, 'shipping_cost': {'discount_value': 0, 'max_discount_in_usd': -1, 'min_cost_in_usd': 0}}),
        ),
    ]
