# Generated by Django 2.2.2 on 2020-11-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20201120_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemedcoupontransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_coupon_transactions', to='order.Order', unique=True),
        ),
    ]
