# Generated by Django 2.2.2 on 2020-11-20 16:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations

from coupon.models import Coupon

default_value_config = {'pack_production_cost': {'discount_value': 0, 'max_discount_in_usd': -1, 'min_cost_in_usd': 0},
                        'pack_shipping_cost': {'discount_value': 0, 'max_discount_in_usd': -1, 'min_cost_in_usd': 0}}


def migrate_coupon_default_value_config(apps, schema_editor):
    Coupon.objects.update(value_config=default_value_config)


class Migration(migrations.Migration):
    dependencies = [
        ('coupon', '0011_auto_20201120_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='value_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=default_value_config),
        ),
        migrations.RunPython(migrate_coupon_default_value_config),
    ]
