# Generated by Django 2.2.2 on 2019-10-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected')], default='0', max_length=2)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('send_time', models.DateTimeField(null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'pending'), ('1', 'sent'), ('2', 'error')], default='0', max_length=2)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected')], default='0', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'unread'), ('1', 'read'), ('2', 'deleted')], default='0', max_length=2)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('type', models.CharField(blank=True, choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected')], default='0', max_length=2, primary_key=True, serialize=False)),
                ('message_title', models.CharField(blank=True, max_length=255, null=True)),
                ('message_content', models.CharField(blank=True, max_length=2000, null=True)),
                ('mail_title', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_content', models.CharField(blank=True, max_length=2000, null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_message', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-type'],
            },
        ),
    ]
