# Generated by Django 2.2.2 on 2019-10-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0004_auto_20191012_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailhistory',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected'), ('2', 'registration_activation_email'), ('3', 'add_payment_prompt'), ('4', 'recharge_notification')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected'), ('2', 'registration_activation_email'), ('3', 'add_payment_prompt'), ('4', 'recharge_notification')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected'), ('2', 'registration_activation_email'), ('3', 'add_payment_prompt'), ('4', 'recharge_notification')], default='0', max_length=2, primary_key=True, serialize=False),
        ),
    ]
