# Generated by Django 2.2.2 on 2019-11-03 15:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0007_auto_20191024_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='parameter_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
