# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0008_template_parameter_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='parameter_list',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
