# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0010_update_owner_id_type'),
    ]

    operations = [
        migrations.RunSQL('DELETE FROM "public"."notification_template" WHERE 1 = 1'),
        migrations.RunSQL('INSERT INTO "public"."notification_template"("type", "message_title", "message_content", "mail_title", "mail_content", "send_email", "send_message", "parameter_list") '
                          + 'VALUES (\'4\', \'Please recharge your payment method\', \'All of your payment method have been out of money. Please recharge them to continue using our service\', \'Hi {mail_title_include}\', \'All of your payment method have been out of money. Please recharge them to continue using our service\', false, false, \'{}\')'
                          + ',(\'7\', \'Order Rejected\', \'<p>You order <a title="View order" href="/u/orders/{order_id}">#{order_id}</a> has been rejected in PrintHolo</p>\', \'Order Rejected\', \'<p>You order {order_id} has been rejected</p>\', false, false, \'a \')'
                          + ',(\'8\', \' \', \' \', \'Order has been rejected in Print Holo\', \'You order {order_id} has been rejected\', false, false, \'Order_id: id của orderHello: EREREER \')'
                          + ',(\'6\', \' \', \' \', \'Order has been canceled in Fulfillment HUB\', \'You order {order_id} has been canceled\', false, false, \'{} \')'
                          + ',(\'2\', \' \', \' \', \'Please active your account {mail_title_include}\', \'Please click on the link to confirm your registration: {mail_content_include}\', false, false, \'{}\')'
                          + ',(\'5\', \'Cancel order success\', \'Your order <a title="View order" href="/u/orders/{order_id}">#{order_id}</a> has been canceled\', \'Cancel order success\', \'You order {order_id} has been canceled\', false, false, \'{} \')'
                          + ',(\'1\', \'Cancel Shipping Request Reject\', \'Your cancel shipping request for order <a title="View order" href="/u/orders/{order_id}">#{order_id}</a> has been rejected\', \'Cancel Shipping Request Reject Shipping Request Approved\', \'Your cancel shipping request for order {order_id} has been rejected\', false, false, \'{}\')'
                          + ',(\'0\', \'Cancel Shipping Request Approved\', \'Your cancel shipping request for order <a title="View order" href="/u/orders/{order_id}">#{order_id}</a> has been approved. The refund will be transfer to your account soon\', \'Cancel Shipping Request Approved\', \'Your cancel shipping request for order {order_id} has been approved. The refund will be transfer to your account soon\', false, false, \'{}\')'
                          + ',(\'3\', \'Please add your payment\', \'<p>Please <a title="Add Payment" href="/u/payments">add your payment</a> before creating products and orders</p>\', \' \', \' \', false, false, \'{}\')')
    ]
