# Generated by Django 2.2.2 on 2020-02-27 09:07

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0014_auto_20200211_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantPrompt',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(blank=True, choices=[('0', 'add_shop'), ('1', 'add_payment_method'), ('2', 'billing_charge_failed')], default='1', max_length=2)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'unread'), ('1', 'read'), ('2', 'deleted')], default='0', max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
