# Generated by Django 2.2.2 on 2019-10-26 15:48

from django.db import migrations

from HUB.models.random_id_model import RandomIDModel
from notification.models import InstantPrompt


def random_id_instant_prompt(apps, schema_editor):
    RandomIDModel.init_random_seq(InstantPrompt)


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0015_instantprompt'),
    ]

    operations = [
        migrations.RunPython(random_id_instant_prompt),
    ]
