# Generated by Django 2.2.2 on 2020-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0017_auto_20200306_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailhistory',
            name='type',
            field=models.CharField(blank=True,
                                   choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected'), ('2', 'registration_activation_email'), ('3', 'add_payment_prompt'), ('4', 'recharge_notification'), ('5', 'cancel_order_success'), ('6', 'cancel_order_success_shop_owner'), ('7', 'order_rejected'), ('8', 'order_rejected_shop_owner'), ('9', 'seller_order_contact_support'), ('10', 'admin_order_contact_support'), ('11', 'admin_refund_failed'), ('12', 'admin_long_invoice_processing')],
                                   default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True,
                                   choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected'), ('2', 'registration_activation_email'), ('3', 'add_payment_prompt'), ('4', 'recharge_notification'), ('5', 'cancel_order_success'), ('6', 'cancel_order_success_shop_owner'), ('7', 'order_rejected'), ('8', 'order_rejected_shop_owner'), ('9', 'seller_order_contact_support'), ('10', 'admin_order_contact_support'), ('11', 'admin_refund_failed'), ('12', 'admin_long_invoice_processing')],
                                   default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(blank=True,
                                   choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected'), ('2', 'registration_activation_email'), ('3', 'add_payment_prompt'), ('4', 'recharge_notification'), ('5', 'cancel_order_success'), ('6', 'cancel_order_success_shop_owner'), ('7', 'order_rejected'), ('8', 'order_rejected_shop_owner'), ('9', 'seller_order_contact_support'), ('10', 'admin_order_contact_support'), ('11', 'admin_refund_failed'), ('12', 'admin_long_invoice_processing')],
                                   default='0', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.RunSQL("INSERT INTO public.notification_template (type, message_title, message_content, mail_title, mail_content, send_email, send_message, parameter_list) VALUES ('12', 'Invoice Long Processing', 'Invoice Long Processing', 'Invoice Long Processing #{invoice_id}', 'INVOICE_ID: #{invoice_id} \n" +
                          "PROCESS_INFO: \n" +
                          "{data}', true, false, 'invoice_id, data');")
    ]
