# Generated by Django 2.2.2 on 2020-07-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_auto_20200717_0919'),
        ('notification', '0020_auto_20200720_0742'),
    ]

    operations = [
    ]
