# Generated by Django 2.2.2 on 2020-07-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_update_noti_content_20200730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailhistory',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected'), ('2', 'registration_activation_email'), ('3', 'add_payment_prompt'), ('4', 'recharge_notification'), ('5', 'cancel_order_success'), ('6', 'cancel_order_success_shop_owner'), ('7', 'order_rejected'), ('8', 'order_rejected_shop_owner'), ('9', 'seller_order_contact_support'), ('11', 'admin_refund_failed'), ('12', 'admin_long_invoice_processing'), ('13', 'forgot_password_email')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected'), ('2', 'registration_activation_email'), ('3', 'add_payment_prompt'), ('4', 'recharge_notification'), ('5', 'cancel_order_success'), ('6', 'cancel_order_success_shop_owner'), ('7', 'order_rejected'), ('8', 'order_rejected_shop_owner'), ('9', 'seller_order_contact_support'), ('11', 'admin_refund_failed'), ('12', 'admin_long_invoice_processing'), ('13', 'forgot_password_email')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'cancel_shipping_approved'), ('1', 'cancel_shipping_rejected'), ('2', 'registration_activation_email'), ('3', 'add_payment_prompt'), ('4', 'recharge_notification'), ('5', 'cancel_order_success'), ('6', 'cancel_order_success_shop_owner'), ('7', 'order_rejected'), ('8', 'order_rejected_shop_owner'), ('9', 'seller_order_contact_support'), ('11', 'admin_refund_failed'), ('12', 'admin_long_invoice_processing'), ('13', 'forgot_password_email')], default='0', max_length=2, primary_key=True, serialize=False),
        ),
    ]
