# Generated by Django 2.2.2 on 2020-08-28 07:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0026_auto_20200813_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
