# Generated by Django 2.2.2 on 2020-11-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0039_update_noti_content_14102020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='mail_content',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
