# Generated by Django 2.2.2 on 2020-11-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0040_auto_20201120_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='mail_content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
