# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0042_update_mail_activation_content'),
    ]

    operations = [
        migrations.RunSQL('DELETE FROM "public"."notification_template" WHERE 1 = 1'),
        migrations.RunSQL(
            'INSERT INTO public.notification_template (type, message_title, message_content, mail_title, mail_content, send_email, send_message, parameter_list)'
            + 'VALUES  (\'8\', \' \', \' \', \'Order has been rejected in Print Holo\', \'You order {order_id} has been rejected\', true, false, \'Order_id: id của orderHello: EREREER \')'
            + ',(\'3\', \'Please add your payment\', \'<p>Please <span class="link-ui" title="Add Payment" path="/u/payments">add your payment</span> before creating products and orders</p>\', \' \', \' \', false, true, \'{}\')'
            + ',(\'5\', \'Cancel order success\', \'Your order <span class="link-ui" title="View order" path="/u/orders/{order_id}">#{order_id}</span> has been canceled\', \'Cancel order success\', \'You order {order_id} has been canceled\', true, true, \'{} \')'
            + ',(\'4\', \'Please recharge your payment method\', \'All of your payment method have been out of money. Please recharge them to continue using our service\', \'Hi {mail_title_include}\', \'All of your payment method have been out of money. Please recharge them to continue using our service\', true, true, \'{}\')'
            + ',(\'7\', \'Order Rejected\', \'<p>Your order <span class="link-ui" title="View order" path="/u/orders/{order_id}">#{order_id}</span> has been rejected in PrintHolo</p>\', \'Order Rejected\', \'<p>You order {order_id} has been rejected</p>\', true, true, \'a \')'
            + ',(\'6\', \' \', \' \', \'Order has been canceled in Fulfillment HUB\', \'You order {order_id} has been canceled\', true, false, \'{} \')'
            + ',(\'1\', \'Cancel Shipping Request Reject\', \'Your cancel shipping request for order <span class="link-ui" title="View order" path="/u/orders/{order_id}">#{order_id}</span> has been rejected\', \'Cancel Shipping Request Reject Shipping Request Approved\', \'Your cancel shipping request for order {order_id} has been rejected\', true, true, \'{}\')'
            + ',(\'0\', \'Cancel Shipping Request Approved\', \'Your cancel shipping request for order <span class="link-ui" title="View order" path="/u/orders/{order_id}">#{order_id}</span> has been approved. The refund will be transfer to your account soon\', \'Cancel Shipping Request Approved\', \'Your cancel shipping request for order {order_id} has been approved. The refund will be transfer to your account soon\', true, true, \'{}\')'
            + ',(\'2\', \' \', \' \', \'Please active your account {mail_title_include}\', \'Please click on the link to confirm your registration: {mail_content_include}\', true, false, \'{}\')'
            + ',(\'13\', \' \', \' \', \'Password reset for {mail_title_include}\', \'Please click on the link to change your password: {mail_content_include}\', true, false, \'{}\')'
            + ',(\'9\', \'\', \'\', \'[Order Support] - Order: {order_id} - {subject}\', \'<table role=\'\'presentation\'\' border=\'\'0\'\' cellpadding=\'\'0\'\' cellspacing=\'\'0\'\' class=\'\'body\'\'> <tr> <td> </td> <td class=\'\'container\'\'> <div class=\'\'content\'\'> <table role=\'\'presentation\'\' class=\'\'main\'\'> <tr> <td class=\'\'wrapper\'\'> <table role=\'\'presentation\'\' border=\'\'0\'\' cellpadding=\'\'0\'\' cellspacing=\'\'0\'\'> <tr> <td> <p>Hi there,</p> <p>At {time}, you sent us an issue about order {order_id}. Below is your issue content:</p> <em>"{content}"</em> <p>This issue was forwarded to our support team and they will response to you as soon as possible. Thank you for this contact.</p> <p>All the best, </p> <p>PrintHolo team</p> </td> </tr> </table> </td> </tr> </table>\', true, false, \'time: time sent issue, order_id: id of order, content: content of issue\')'
            + ',(\'11\', \'Refund Error\', \'Refund Error\', \'Cannot Process Refund #{refund_id} of Invoice #{invoice_id}\', \'Cannot Process Refund #{refund_id} of Invoice #{invoice_id} with amount ${amount}\', true, false, \'refund_id, invoice_id, amount\')'
            + ',(\'14\', \'Ticket Resolved\', \'Your ticket <span class="link-ui" title="View ticket" path="/u/tickets/{ticket_id}">#{ticket_id}</span> has been resolved\', \'\', \'\', false, true, \'{}\')'
            + ',(\'15\', \'Product deleted error in shop\', \'Product <span class="link-ui" title="View product" path="/u/products/{product_id}"><b>{product_name}</b></span> delete error in shop <b>{shop_list}</b>.\', \' \', \'\', false, true, \'{}\')'
            + ',(\'16\', \'Order Shipping Address Rejected\', \'<p>Shipping address in order <span class="link-ui" title="View order" path="/u/orders/{order_id}">#{order_id}</span> has not been updated in PrintHolo</p>\', \'Order Shipping Address Rejected\', \'<p>Shipping address in order {order_id} has not been updated</p>\', true, true, \'a \')'
            + ',(\'17\', \'\', \'\', \'PrintHolo account\', \'<div>Your PrintHolo account is created with email: {email} and automatically generated password: {password}. Please go this link: {profile_link} and change the password</div>\', true, false, \' \')'
        )
    ]
