# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0043_add_email_notifi_content'),
    ]

    operations = [
        migrations.RunSQL(
            """
            update public.notification_template set mail_content = '<p><img src="https://lh4.googleusercontent.com/1UqL4IUvocGOiu0lij7g_ar1DatLz4f36iK6IaR9G-wR0Lrt3utHtzmQ7hnYVxv_wzA_JtMOnvDxUgD2UrAQIIoV4jsUP-ym7eZT6cpzxLyJJeBDTpGX=w1280" width="33.33%" /></p>
<p><img src="https://lh6.googleusercontent.com/IpmXsqfSJW-j4CqeJd5ZIiZ7CdHVGjF0Tqx3DsDas6bo0fOBsP0dZRq_Mtp3fWw2I4N75Zmz3pv6Azxw3i5dVvJoJqY1oLM8BaIaPrxWBE2PPlDLp00=w1280" width="100%" /></p>
<p dir="ltr">Hi, {user_name}, We are so happy to have you on our team. Let''s do a quick introduction!</p>
<p dir="ltr">PrintHolo, we are built to help you to make your Print On Demand business life much easier. To create and sell your own design products is faster, smarter. Are you ready to scale your business today with us?</p>
<div style="line-height: 1.4; word-wrap: break-word; font-family: sans-serif; font-size: 16px; box-sizing: border-box; display: inline-block; vertical-align: middle; width: 20%;"><a style="word-wrap: break-word; line-height: 1.4; font-family: Helvetica,Arial,sans-serif; font-size: 14px; display: block; background-color: rgba(30,108,147,1); color: white; text-decoration: none; width: 100%; text-align: center; padding: 10px;" href="{active_link}">Get started now</a></div>
<h2><span style="color: #236FA1;"><strong>Make your own personalized products</strong></span></h2>
<p dir="ltr">With PrintHolo, your customizing mockups is much easier than ever. Using a user-friendly drag &amp; drop method that will help you design quickly and easily your product mockups. <strong>Easy-to-use Mockup Generator</strong></p>
<h2><span style="color: #236FA1;"><strong>Wide Selection of Products &amp; Pricing</strong></span></h2>
<p dir="ltr"><strong>Let''s explore</strong><strong> </strong><strong>all</strong><strong> unique products</strong> we have such as Tshirt, Hoodie, Zip Hoodie, Sweatshirt, Mask, Neck gaiter, Hawaii Shirt, etc . Then create and sell custom print-on-demand products under your own brand.</p>
<h2><span style="color: #236FA1;"><strong>100% in-house manufacturing</strong></span></h2>
<div>All Printholo products are manufactured in our facility in Vietnam. We''re able to keep the lead time and 100% the quality under control so we can guarantee that you are receiving the best product possible.</div>
<div style="line-height: 1.4; word-wrap: break-word; font-family: sans-serif; font-size: 16px; box-sizing: border-box; display: inline-block; vertical-align: middle; width: 20%;"><a style="word-wrap: break-word; line-height: 1.4; font-family: Helvetica,Arial,sans-serif; font-size: 14px; display: block; background-color: rgba(30,108,147,1); color: white; text-decoration: none; width: 100%; text-align: center; padding: 10px;" href="{active_link}">Start designing now</a></div>' where type = '2'
            """
        )
    ]
