# Generated by Django 2.2.2 on 2020-12-02 08:13
from django.contrib.auth import get_user_model
from django.db import migrations

from notification.enums.instant_prompt_types import InstantPromptType
from notification.enums.message_statuses import MessageStatus
from notification.models import InstantPrompt

User = get_user_model()


def update_sample_product_execution(apps, schema_editor):
    instant_prompt_to_create = []
    for user in User.objects.all():
        instant_prompt_to_create.append(
            InstantPrompt(owner=user, type=InstantPromptType.ORDER_PROCESSING_TIME, status=MessageStatus.UNREAD))
    InstantPrompt.objects.bulk_create(instant_prompt_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0045_auto_20201202_0813'),
    ]

    operations = [
        # migrations.RunPython(update_sample_product_execution),
    ]
