# Generated by Django 2.2.2 on 2020-12-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0100_order'),
        ('notification', '0048_auto_20201208_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTrackingNotification',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('receive_email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('1', 'order shipping'), ('2', 'order delivered')], max_length=1)),
                ('sent_time', models.DateTimeField(default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'notification_order_tracking',
            },
        ),
    ]
