# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0049_ordertrackingnotification'),
    ]

    operations = [
        migrations.RunSQL(
            'INSERT INTO public.notification_template (type, message_title, message_content, mail_title, mail_content, send_email, send_message, parameter_list) VALUES '
            + '(\'18\', \'\', \'\', \'Shipping order\', \'<div>Your order #{order_id} is completely fulfilled and shipping</div>\', true, false, \' \'),'
            + '(\'19\', \'\', \'\', \'Delivered order\', \'<div>Order #{order_id} is delivered</div>\', true, false, \' \')'
        ),
    ]
