# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0051_auto_20201230_0653'),
    ]

    operations = [
        migrations.RunSQL(
            'UPDATE public.notification_template set message_title = \'Order shipping\' where type=\'18\';'
        ),
        migrations.RunSQL(
            'UPDATE public.notification_template set message_title = \'Order delivered\' where type=\'19\';'
        ),
    ]
