# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0052_update_order_tracking_notification'),
    ]

    operations = [
        migrations.RunSQL(
            'INSERT INTO public.notification_template (type, message_title, message_content, mail_title, mail_content, send_email, send_message, parameter_list) VALUES '
            + '(\'20\', \'\', \'\', \'Authenication Warining\', \'Please click in {reset_password_link}\', true, false, \' \'),'
            + '(\'21\', \'\', \'\', \'Welcome to Printholo\', \'Hi {user_name}\', true, false, \' \')'
        ),
    ]
