# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0055_auto_20210308_0402'),
    ]

    operations = [
        migrations.RunSQL(
            'INSERT INTO public.notification_template (type, message_title, message_content, mail_title, mail_content, send_email, send_message, parameter_list) VALUES '
            + '(\'22\', \'\', \'\', \'Unprofitable order\', \'<div>New order #{order_id} is unprofitable. printholo cost: {ph_cost}, fulfillment cost: {ffm_cost}</div>\', true, false, \' \')'
        ),
    ]
