# Generated by Django 2.2.2 on 2021-03-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0013_custommailsender'),
        ('notification', '0060_auto_20210316_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_send_custom_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='mail_sender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_tools.CustomMailSender'),
        ),
    ]
