# Generated by Django 2.2.2 on 2021-03-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0061_auto_20210318_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='mail_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_tools.CustomMailSender'),
        ),
    ]
