# Generated by Django 2.2.2 on 2021-03-19 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0062_auto_20210318_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='mail_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_sender', to='admin_tools.CustomMailSender'),
        ),
    ]
