# Generated by Django 2.2.2 on 2021-03-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0063_auto_20210319_0921'),
        ('notification', '0063_auto_20210322_0840'),
    ]

    operations = [
    ]
