# Generated by Django 2.2.2 on 2021-05-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0064_alter_meta_config_1903_2021'),
        ('notification', '0064_merge_20210322_1106'),
    ]

    operations = [
    ]
