# Generated by Django 2.2.2 on 2019-10-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCommunicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill')], default='0', max_length=2)),
                ('object_id', models.PositiveIntegerField()),
                ('status_code', models.IntegerField(null=True)),
                ('response_body', models.TextField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'service_communication_log',
                'ordering': ['id'],
            },
        ),
    ]
