# Generated by Django 2.2.2 on 2019-10-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('5', 'fulfill_update_shipping_address')], default='0', max_length=2),
        ),
    ]
