# Generated by Django 2.2.2 on 2019-10-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0002_auto_20191012_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
