# Generated by Django 2.2.2 on 2019-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0003_auto_20191024_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
