# Generated by Django 2.2.2 on 2019-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0007_auto_20191030_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('6', 'fulfill_update_shipping_address'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app')], default='0', max_length=2),
        ),
    ]
