# Generated by Django 2.2 on 2019-12-24 09:59

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('service_communication', '0011_auto_20191118_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookJob',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.BigIntegerField()),
                ('type', models.CharField(
                    choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('6', 'fulfill_update_shipping_address'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('12', 'fulfill_update_artwork'), ('13', 'adapter_get_shipping_rate')],
                    max_length=2)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('attempted_count', models.IntegerField(blank=True, default=0)),
                ('max_attempt_count', models.IntegerField(blank=True, default=-1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
