# Generated by Django 2.2 on 2019-12-24 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0012_webhookjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookjob',
            old_name='type',
            new_name='request_type',
        ),
    ]
