# Generated by Django 2.2 on 2019-12-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0013_auto_20191224_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookjob',
            name='status',
            field=models.CharField(choices=[('1', 'success'), ('2', 'pending'), ('3', 'failed')], default='2', max_length=2),
        ),
    ]
