# Generated by Django 2.2 on 2019-12-25 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0014_webhookjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecommunicationlog',
            name='webhook_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='service_communication.WebhookJob'),
        ),
    ]
