# Generated by Django 2.2.2 on 2020-01-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0017_auto_20200103_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'),
                                                        ('13', 'adapter_get_shipping_rate'), ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='webhookjob',
            name='request_type',
            field=models.CharField(
                choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('13', 'adapter_get_shipping_rate'),
                         ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids')], max_length=2),
        ),
    ]
