# Generated by Django 2.2 on 2020-01-07 16:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0018_auto_20200104_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookjob',
            name='relate_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
