# Generated by Django 2.2 on 2020-01-09 03:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0021_auto_20200108_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookjob',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='webhookjob',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='service_com_tsv_met_71ad0c_gin'),
        ),
    ]
