# Generated by Django 2.2 on 2020-01-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0024_auto_20200109_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookjob',
            name='is_aborted',
            field=models.BooleanField(default=False),
        ),
    ]
