# Generated by Django 2.2 on 2020-01-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0025_webhookjob_is_aborted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookjob',
            name='is_aborted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
