# Generated by Django 2.2 on 2020-01-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0026_auto_20200109_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookjob',
            name='is_aborted',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
