# Generated by Django 2.2.2 on 2020-06-30 08:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0029_auto_20200220_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAuthenticationConfig',
            fields=[
                ('service_name', models.CharField(choices=[('fresh_desk_webhook', 'fresh_desk_webhook')], max_length=20, primary_key=True, serialize=False)),
                ('authentication_type', models.CharField(choices=[('header', 'header'), ('h_mac', 'h_mac'), ('ip', 'ip')], db_index=True, max_length=10)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'db_table': 'service_communication_authentication_config',
            },
        ),
        migrations.RunSQL("INSERT INTO service_communication_authentication_config (service_name, authentication_type, meta) VALUES ('fresh_desk_webhook', 'header', '{\"Authorization\": \"printholo@12345678\"}');")
    ]
