# Generated by Django 2.2.2 on 2020-07-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0030_serviceauthenticationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('13', 'adapter_get_shipping_rate'), ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids'), ('16', 'adapter_update_order'), ('17', 'adapter_delete_product'), ('19', 'adapter_get_product')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='webhookjob',
            name='request_type',
            field=models.CharField(choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('13', 'adapter_get_shipping_rate'), ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids'), ('16', 'adapter_update_order'), ('17', 'adapter_delete_product'), ('19', 'adapter_get_product')], db_index=True, max_length=2),
        ),
    ]
