# Generated by Django 2.2.2 on 2020-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0034_auto_20200806_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookjob',
            name='status',
            field=models.CharField(choices=[('1', 'success'), ('2', 'pending'), ('3', 'failed'), ('4', 'queued')], db_index=True, default='2', max_length=2),
        ),
    ]
