# Generated by Django 2.2.2 on 2020-08-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0035_auto_20200812_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleinfo',
            name='schedule_type',
            field=models.CharField(choices=[('1', 'auto_scan_support_ticket')], db_index=True, default='1', max_length=10, unique=True),
        ),
    ]
