# Generated by Django 2.2.2 on 2020-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0036_auto_20200816_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scheduleinfo',
            name='schedule_type',
            field=models.CharField(choices=[('1', 'auto_scan_support_ticket'), ('2', 'auto_renew_paypal_token')], db_index=True, default='1', max_length=10, unique=True),
        ),
    ]
