# Generated by Django 2.2.2 on 2020-09-21 17:54

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0038_auto_20200921_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookjob',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='webhookjob',
            name='relate_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
