# Generated by Django 2.2.2 on 2020-10-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0041_auto_20201012_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='object_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
