# Generated by Django 2.2.2 on 2020-10-20 04:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0042_auto_20201017_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecommunicationlog',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='servicecommunicationlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='service_com_tsv_met_051b78_gin'),
        ),
    ]
