# Generated by Django 2.2.2 on 2020-10-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0044_auto_20201020_create_text_search_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('13', 'adapter_get_shipping_rate'), ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids'), ('16', 'adapter_update_order'), ('17', 'adapter_delete_product'), ('19', 'adapter_get_product'), ('20', 'mockup_generate_artwork_fusion'), ('21', 'adapter_post_init_app'), ('22', 'fulfill_production_statistic'), ('23', 'fulfill_shipping_statistic')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='webhookjob',
            name='request_type',
            field=models.CharField(choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('13', 'adapter_get_shipping_rate'), ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids'), ('16', 'adapter_update_order'), ('17', 'adapter_delete_product'), ('19', 'adapter_get_product'), ('20', 'mockup_generate_artwork_fusion'), ('21', 'adapter_post_init_app'), ('22', 'fulfill_production_statistic'), ('23', 'fulfill_shipping_statistic')], db_index=True, max_length=2),
        ),
    ]
