# Generated by Django 2.2.2 on 2020-11-30 06:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_communication', '0045_auto_20201029_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedRequest',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.BigIntegerField()),
                ('request_type', models.CharField(choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('13', 'adapter_get_shipping_rate'), ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids'), ('16', 'adapter_update_order'), ('17', 'adapter_delete_product'), ('19', 'adapter_get_product'), ('20', 'mockup_generate_artwork_fusion'), ('21', 'adapter_post_init_app'), ('22', 'fulfill_production_statistic'), ('23', 'fulfill_shipping_statistic')], db_index=True, max_length=2)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'rejected'), ('2', 'resolved')], db_index=True, default='0', max_length=2)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tsv_metadata_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('last_update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_order_rejected_by_fulfills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_communication_rejected_request',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddIndex(
            model_name='rejectedrequest',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='service_com_tsv_met_25ee4b_gin'),
        ),
    ]
