# Generated by Django 2.2.2 on 2020-11-30 10:18

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('service_communication', '0047_auto_20201130_create_text_search_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingWebhook',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.BigIntegerField()),
                ('type', models.CharField(choices=[('0', 'fulfill_process_order'), ('1', 'fulfill_update_tracking'), ('2', 'fulfill_reject_order')], db_index=True, default='0', max_length=2)),
                ('body_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'resolved'), ('2', 'error'), ('3', 'cancelled')], db_index=True, default='0', max_length=2)),
                ('process_description', models.CharField(blank=True, max_length=255, null=True)),
                ('process_count', models.SmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tsv_metadata_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'service_communication_incoming_webhook',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddIndex(
            model_name='incomingwebhook',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='service_com_tsv_met_5834a2_gin'),
        ),
    ]
