# Generated by Django 2.2.2 on 2020-12-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0049_auto_20201130_create_text_search_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingwebhook',
            name='type',
            field=models.CharField(choices=[('0', 'fulfill_process_order'), ('1', 'fulfill_update_tracking'), ('2', 'fulfill_reject_order'), ('3', 'paypal_sale_transaction_update'), ('4', 'paypal_capture_transaction_update')], db_index=True, default='0', max_length=2),
        ),
    ]
