# Generated by Django 2.2.2 on 2020-12-11 09:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0050_auto_20201211_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingwebhook',
            name='body_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomingwebhook',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomingwebhook',
            name='object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
