# Generated by Django 2.2.2 on 2020-12-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0051_auto_20201211_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingwebhook',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
