# Generated by Django 2.2.2 on 2020-12-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0052_auto_20201211_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookjob',
            name='status',
            field=models.CharField(choices=[('1', 'success'), ('2', 'pending'), ('3', 'failed'), ('4', 'queued'), ('5', 'processing')], db_index=True, default='2', max_length=2),
        ),
    ]
