# Generated by Django 2.2.2 on 2021-03-04 02:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0054_auto_20210126_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryLog',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('1', 'send_email')], max_length=1)),
                ('note', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service_communication_celery_log',
                'ordering': ['id', 'create_time'],
            },
        ),
    ]
