# Generated by Django 2.2.2 on 2021-03-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0055_celerylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedrequest',
            name='request_type',
            field=models.CharField(choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('13', 'adapter_get_shipping_rate'), ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids'), ('16', 'adapter_update_order'), ('17', 'adapter_delete_product'), ('19', 'adapter_get_product'), ('20', 'mockup_generate_artwork_fusion'), ('21', 'adapter_post_init_app'), ('22', 'fulfill_production_statistic'), ('23', 'fulfill_shipping_statistic'), ('24', 'adapter_check_shop_location'), ('25', 'payment_paypal_request'), ('26', 'payment_payoneer_charge')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='servicecommunicationlog',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('13', 'adapter_get_shipping_rate'), ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids'), ('16', 'adapter_update_order'), ('17', 'adapter_delete_product'), ('19', 'adapter_get_product'), ('20', 'mockup_generate_artwork_fusion'), ('21', 'adapter_post_init_app'), ('22', 'fulfill_production_statistic'), ('23', 'fulfill_shipping_statistic'), ('24', 'adapter_check_shop_location'), ('25', 'payment_paypal_request'), ('26', 'payment_payoneer_charge')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='webhookjob',
            name='request_type',
            field=models.CharField(choices=[('0', 'fulfill_push_order'), ('1', 'fulfill_push_artwork'), ('2', 'fulfill_mark_as_paid'), ('12', 'fulfill_update_artwork'), ('6', 'fulfill_update_shipping_address'), ('3', 'adapter_fulfill_order'), ('4', 'adapter_update_tracking'), ('5', 'adapter_complete_fulfill'), ('7', 'adapter_add_new_product'), ('8', 'adapter_update_product'), ('9', 'adapter_uninstall_app'), ('10', 'adapter_init_app'), ('11', 'adapter_list_order'), ('13', 'adapter_get_shipping_rate'), ('14', 'easy_post_get_tracking_status'), ('15', 'adapter_list_order_by_ids'), ('16', 'adapter_update_order'), ('17', 'adapter_delete_product'), ('19', 'adapter_get_product'), ('20', 'mockup_generate_artwork_fusion'), ('21', 'adapter_post_init_app'), ('22', 'fulfill_production_statistic'), ('23', 'fulfill_shipping_statistic'), ('24', 'adapter_check_shop_location'), ('25', 'payment_paypal_request'), ('26', 'payment_payoneer_charge')], db_index=True, max_length=2),
        ),
    ]
