# Generated by Django 2.2.2 on 2021-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0056_auto_20210310_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceauthenticationconfig',
            name='service_name',
            field=models.CharField(
                choices=[('fresh_desk_webhook', 'fresh_desk_webhook'), ('ecommerce_adapter', 'ecommerce_adapter'),
                         ('fulfillment', 'fulfillment')], max_length=20, primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            "INSERT INTO public.service_communication_authentication_config (service_name, authentication_type, meta) VALUES ('fulfillment', 'h_mac', '{\"algorithm\": \"sha256\", \"enable\": true}');")
    ]
