# Generated by Django 2.2.2 on 2021-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service_communication', '0057_auto_20210323_0958'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE public.service_communication_authentication_config SET meta = '{\"algorithm\": \"sha256\", \"enable\": false}' where service_name='fulfillment';")
    ]
