# Generated by Django 2.2.2 on 2021-04-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0060_request_logs_recreate_text_search_trigger_20210331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceauthenticationconfig',
            options={'ordering': ['service_name']},
        ),
    ]
