# Generated by Django 2.2.2 on 2021-04-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_communication', '0062_update_old_request_logs'),
        ('service_communication', '0062_auto_20210420_1047'),
    ]

    operations = [
    ]
