# Generated by Django 2.2.2 on 2020-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paypal_payment', '0001_initial_20200221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalpaymentmethod',
            name='agreement_token',
        ),
        migrations.AddField(
            model_name='paypalpaymentmethod',
            name='agreement_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
