# Generated by Django 2.2.2 on 2020-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paypal_payment', '0002_auto_20200221_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpaymentmethod',
            name='agreement_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
