# Generated by Django 2.2.2 on 2020-02-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paypal_payment', '0003_auto_20200222_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpaymentmethod',
            name='payee_id',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
