# Generated by Django 2.2.2 on 2020-02-22 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('paypal_payment', '0004_paypalpaymentmethod_payee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypalpaymentmethod',
            old_name='payee_id',
            new_name='payer_id',
        ),
    ]
