# Generated by Django 2.2.2 on 2019-10-26 15:48

from django.db import migrations

from HUB.models.random_id_model import RandomIDModel
from billing.sub_apps.paypal_payment.models import PaypalPaymentMethod


def random_id_paypal_method(apps, schema_editor):
    RandomIDModel.init_random_seq(PaypalPaymentMethod)


class Migration(migrations.Migration):
    dependencies = [
        ('paypal_payment', '0005_auto_20200222_0818'),
    ]

    operations = [
        migrations.RunPython(random_id_paypal_method),
    ]
