# Generated by Django 2.2.2 on 2020-02-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paypal_payment', '0006_random_id_paypal_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpaymentmethod',
            name='type',
            field=models.CharField(blank=True, db_index=True, default='pay_pal_account', max_length=50),
        ),
    ]
