# Generated by Django 2.2.2 on 2020-02-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paypal_payment', '0007_auto_20200227_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpaymentmethod',
            name='payer_id',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
