# Generated by Django 2.2.2 on 2020-02-27 09:01

from django.db import migrations
from django.db.models import Count, Max

from billing.sub_apps.paypal_payment.models import PaypalPaymentMethod


def remove_duplicated_payment_method_with_payer_id(apps, schema_editor):
    duplicated_payment_methods = PaypalPaymentMethod.objects.values("payer_id").order_by().annotate(
        count=Count("payer_id"), max_id=Max("id")).filter(count__gte=2)
    preserved_payment_method_ids = []
    removal_required_payment_method_payer_ids = []
    for payment_method_obj in duplicated_payment_methods:
        preserved_payment_method_ids.append(payment_method_obj.get("max_id"))
        removal_required_payment_method_payer_ids.append(payment_method_obj.get("payer_id"))
    PaypalPaymentMethod.objects.filter(payer_id__in=removal_required_payment_method_payer_ids).exclude(
        id__in=preserved_payment_method_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('paypal_payment', '0008_auto_20200228_0230'),
    ]

    operations = [
        migrations.RunPython(remove_duplicated_payment_method_with_payer_id),
    ]
