# Generated by Django 2.2.2 on 2020-05-31 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0026_auto_20200531_2007'),
        ('combine_payment', '0007_auto_20200317_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProcessInfo',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=50, null=True)),
                ('worker_host', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_info', to='billing.Invoice')),
                ('payment_methods', models.ManyToManyField(to='combine_payment.GeneralPaymentMethod')),
            ],
        ),
    ]
