# Generated by Django 2.2.2 on 2020-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_payment_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceprocessinfo',
            name='payment_methods',
            field=models.ManyToManyField(db_table='worker_payment_processor_info_methods', to='combine_payment.GeneralPaymentMethod'),
        ),
        migrations.AlterModelTable(
            name='invoiceprocessinfo',
            table='worker_payment_processor_info',
        ),
    ]
