# Generated by Django 2.2.2 on 2020-08-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_payment_processor', '0002_auto_20200605_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceprocessinfo',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='invoiceprocessinfo',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='invoiceprocessinfo',
            name='payment_methods',
        ),
        migrations.AlterModelTable(
            name='invoiceprocessinfo',
            table='billing_invoice_processor_info',
        ),
    ]
