# Generated by Django 2.2.2 on 2020-08-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combine_payment', '0007_auto_20200317_0911'),
        ('worker_payment_processor', '0003_auto_20200828_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProcessInfoPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.SmallIntegerField(default=0)),
                ('invoice_process_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_mappings', to='worker_payment_processor.InvoiceProcessInfo')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_process_info_mappings', to='combine_payment.GeneralPaymentMethod')),
            ],
            options={
                'db_table': 'billing_invoice_process_info_payment_method',
                'ordering': ['ordinal_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='invoiceprocessinfo',
            name='payment_methods',
            field=models.ManyToManyField(related_name='invoice_processor_info_set', through='worker_payment_processor.InvoiceProcessInfoPaymentMethod', to='combine_payment.GeneralPaymentMethod'),
        ),
    ]
