# Generated by Django 2.2.2 on 2020-06-30 08:52

import django.db.models.deletion
from django.db import migrations, models

from HUB.models.random_id_model import RandomIDModel
from support.models import SupportTicket


def random_id(apps, schema_editor):
    RandomIDModel.init_random_seq(SupportTicket)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ticket_id', models.BigIntegerField(db_index=True)),
                ('object_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('2', 'open'), ('3', 'pending'), ('4', 'resolved'), ('5', 'closed')], default='2', max_length=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'support_ticket',
            },
        ),
        migrations.RunPython(random_id),
    ]
