# Generated by Django 2.2.2 on 2020-06-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketSupport',
            new_name='SupportTicket',
        ),
    ]
