# Generated by Django 2.2.2 on 2020-07-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('support', '0002_auto_20200630_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='object_id',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='type',
            field=models.CharField(choices=[('2', 'order'), ('3', 'product')], default='2', max_length=1),
        ),
        migrations.CreateModel(
            name='SupportTicketTarget',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.BigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.SupportTicket')),
            ],
            options={
                'db_table': 'support_ticket_target',
            },
        ),
    ]
