# Generated by Django 2.2.2 on 2020-07-06 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20200706_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticket',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
