# Generated by Django 2.2.2 on 2020-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20200707_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_reply',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
