# Generated by Django 2.2.2 on 2020-07-16 04:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20200715_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketConversation',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='support.SupportTicket')),
            ],
            options={
                'db_table': 'support_ticket_conversation',
            },
        ),
    ]
