# Generated by Django 2.2.2 on 2020-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_supportticketconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='read_conversation',
            field=models.BooleanField(default=False),
        ),
    ]
