# Generated by Django 2.2.2 on 2020-07-17 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_supportticket_read_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketconversation',
            name='conversation_id',
            field=models.BigIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticketconversation',
            name='create_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticketconversation',
            name='paging',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supportticketconversation',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
