# Generated by Django 2.2 on 2019-11-12 08:18

from django.db import migrations

def migrate_conversation_id(apps, schema_editor):
    SupportTicketConversation = apps.get_model("support", "SupportTicketConversation")
    for conversation in SupportTicketConversation.objects.all():
        conversation.conversation_id = conversation.meta['id']
        conversation.save()


class Migration(migrations.Migration):
    dependencies = [
        ('support', '0010_auto_20200717_0607'),
    ]

    operations = [
        migrations.RunPython(migrate_conversation_id),
    ]
