# Generated by Django 2.2.2 on 2020-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_auto_20200717_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
