# Generated by Django 2.2.2 on 2020-07-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_supportticket_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-update_time']},
        ),
        migrations.AlterModelOptions(
            name='supportticketconversation',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='update_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
