# Generated by Django 2.2.2 on 2020-07-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_auto_20200720_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterModelOptions(
            name='supportticketconversation',
            options={'ordering': ['create_time']},
        ),
    ]
