# Generated by Django 2.2.2 on 2020-07-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_auto_20200720_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='name',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
