# Generated by Django 2.2.2 on 2020-07-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20200722_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='need_update',
            field=models.BooleanField(default=False),
        ),
    ]
