# Generated by Django 2.2.2 on 2020-07-27 02:30

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_supportticket_need_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
