# Generated by Django 2.2.2 on 2020-07-27 03:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_supportticket_tsv_metadata_search'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supportticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='support_tic_tsv_met_21b123_gin'),
        ),
    ]
