# Generated by Django 2.2.2 on 2020-07-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_auto_20200727_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticketconversation',
            name='paging',
        ),
        migrations.AddField(
            model_name='supportticketconversation',
            name='customer_send',
            field=models.BooleanField(default=False),
        ),
    ]
