# Generated by Django 2.2 on 2019-11-12 08:18

from django.db import migrations

from support.function.is_customer_send import is_customer_send


def migrate_customer_send(apps, schema_editor):
    SupportTicketConversation = apps.get_model("support", "SupportTicketConversation")
    conversations = SupportTicketConversation.objects.all()
    for conversation in conversations:
        conversation.customer_send = is_customer_send(conversation.meta)
    SupportTicketConversation.objects.bulk_update(conversations, ['customer_send'])


class Migration(migrations.Migration):
    dependencies = [
        ('support', '0021_auto_20200727_0606'),
    ]

    operations = [
        migrations.RunPython(migrate_customer_send),
    ]
