# Generated by Django 2.2.2 on 2020-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0024_auto_20200728_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
