# Generated by Django 2.2.2 on 2020-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0025_supportticket_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='customer_last_reply',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
