# Generated by Django 2.2.2 on 2020-11-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('1', 'active'), ('2', 'inactive')], db_index=True, default='1', max_length=2)),
                ('header_html', models.CharField(max_length=3000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_template',
                'ordering': ['id'],
            },
        ),
    ]
