# Generated by Django 2.2.2 on 2020-10-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractProductStatistic',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ph_product_title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('ffm_product_title', models.CharField(max_length=255, null=True, verbose_name='Slug')),
                ('production_time_default', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_production_time_default', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_time_default', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_shipping_time_default', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_index', models.SmallIntegerField(default=0, verbose_name='Sort Index')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abstract Product Statistic',
                'verbose_name_plural': 'Abstract Products Statistic',
                'db_table': 'abstract_product_statistic',
                'ordering': ['sort_index', 'id'],
            },
        ),
    ]
