# Generated by Django 2.2.2 on 2020-10-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTimeStatistic',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('point', models.DateTimeField()),
                ('average_time', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abstract Product Statistic',
                'verbose_name_plural': 'Abstract Products Statistic',
                'db_table': 'shipping_time_statistic',
                'ordering': ['point', 'id'],
            },
        ),
    ]
