# Generated by Django 2.2.2 on 2020-10-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_shippingtimestatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingtimestatistic',
            name='average_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
