# Generated by Django 2.2.2 on 2020-11-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_auto_20201030_0418'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='abstractproductstatistic',
            table='statistic_abstract_product',
        ),
        migrations.AlterModelTable(
            name='shippingtimestatistic',
            table='statistic_shipping_time',
        ),
    ]
