# Generated by Django 2.2.2 on 2020-11-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_auto_20201103_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductstatistic',
            name='sku',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
