from HUB import settings


class PublicFileType:
    PRODUCT_PREVIEW_THUMBNAIL = 'PRODUCT_PREVIEW_THUMBNAIL'
    PRODUCT_DESIGN_TEMPLATE = 'PRODUCT_DESIGN_TEMPLATE'
    PRODUCT_SAMPLE_MOCKUP = 'PRODUCT_SAMPLE_MOCKUP'
    PRODUCT_SIDE_BACKGROUND = 'PRODUCT_SIDE_BACKGROUND'
    PRODUCT_SAMPLE_MOCKUP_BACKGROUND = 'PRODUCT_SAMPLE_MOCKUP_BACKGROUND'
    CUSTOM = 'CUSTOM'
    USER_PRODUCT_MOCKUP = 'USER_PRODUCT_MOCKUP'
    USER_FONT = 'USER_FONT'
    PNG_TEMPLATE = 'PNG_TEMPLATE'


FILE_TYPE_TO_DIRECTORY = {
    "PRODUCT_PREVIEW_THUMBNAIL": settings.PRODUCT_PREVIEW_THUMBNAIL_DIRECTORY,
    "PRODUCT_DESIGN_TEMPLATE": settings.PRODUCT_DESIGN_TEMPLATE_DIRECTORY,
    "PRODUCT_SAMPLE_MOCKUP": settings.PRODUCT_SAMPLE_MOCKUP_DIRECTORY,
    'PRODUCT_SIDE_BACKGROUND': settings.PRODUCT_SIDE_BACKGROUND_DIRECTORY,
    'PRODUCT_SAMPLE_MOCKUP_BACKGROUND': settings.SAMPLE_MOCKUP_BACKGROUND_DIRECTORY,
    'CUSTOM': '',
    'USER_PRODUCT_MOCKUP': settings.USER_PRODUCT_MOCKUP,
    'USER_FONT': settings.USER_FONT,
    'PNG_TEMPLATE': settings.PRODUCT_PNG_TEMPLATE_DIRECTORY
}
