from HUB.constants.celery_task import CeleryTask


class WebhookJobQueueID:
    FULFILLMENT_ORDER = "1"
    FULFILLMENT_PRODUCT = "2"
    ADAPTER_ORDER = "3"
    ADAPTER_PRODUCT = "4"
    EX_ADAPTER_SHOP_USER_PRODUCT_FROM_OTHERS = "5"
    MOCKUP_ARTWORK_FUSION = "6"
    ADAPTER_APP = "7"
    ADAPTER_SHOP = "8"


WEBHOOK_JOB_QUEUE_IDS_CHOICES = [
    (WebhookJobQueueID.FULFILLMENT_ORDER, CeleryTask.TASK_RUN_WEBHOOK_JOB_FULFILLMENT_ORDER),
    (WebhookJobQueueID.FULFILLMENT_PRODUCT, CeleryTask.TASK_RUN_WEBHOOK_JOB_FULFILLMENT_PRODUCT),
    (WebhookJobQueueID.ADAPTER_ORDER, CeleryTask.TASK_RUN_WEBHOOK_JOB_ADAPTER_ORDER),
    (WebhookJobQueueID.ADAPTER_PRODUCT, CeleryTask.TASK_RUN_WEBHOOK_JOB_ADAPTER_PRODUCT),
    (WebhookJobQueueID.EX_ADAPTER_SHOP_USER_PRODUCT_FROM_OTHERS, CeleryTask.TASK_RUN_WEBHOOK_JOB_EX_ADAPTER_SHOP_USER_PRODUCT_FROM_OTHERS),
    (WebhookJobQueueID.MOCKUP_ARTWORK_FUSION, CeleryTask.TASK_RUN_WEBHOOK_JOB_MOCKUP_ARTWORK_FUSION),
    (WebhookJobQueueID.ADAPTER_APP, CeleryTask.TASK_RUN_WEBHOOK_JOB_ADAPTER_APP),
    (WebhookJobQueueID.ADAPTER_SHOP, CeleryTask.TASK_RUN_WEBHOOK_JOB_ADAPTER_SHOP)
]
