ABSTRACT_PRODUCT_CATEGORY_CACHE_KEY_PREFIX = "abstractcategory_"
ABSTRACT_PRODUCT_CACHE_KEY_PREFIX = "abstractproduct_"
ABSTRACT_PRODUCT_PRICING_CACHE_KEY_PREFIX = "abstractproductpricing_"
ABSTRACT_PRODUCT_MOCKUP_INFO_CACHE_KEY_PREFIX = "abstractproductmockup_"
ABSTRACT_PRODUCT_CACHE_TIMEOUT = 60 * 60 * 24 * 7
