# Generated by Django 2.2.2 on 2019-10-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('system_metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Commerce Platform',
                'verbose_name_plural': 'E-Commerce Platforms',
                'db_table': 'ecommerce',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderScanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('last_id', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'User Product Artwork',
                'verbose_name_plural': 'User Product Artworks',
                'db_table': 'order_scan_info',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('access_token', models.TextField()),
                ('location_id', models.BigIntegerField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.SET_DEFAULT, to='system_metadata.CurrencyExchangeRate')),
                ('ecommerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Ecommerce')),
            ],
            options={
                'db_table': 'shop',
                'ordering': ['id'],
            },
        ),
    ]
