# Generated by Django 2.2.2 on 2019-10-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_auto_20191005_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
