# Generated by Django 2.2.2 on 2019-10-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0004_auto_20191024_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderscaninfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
