# Generated by Django 2.2.2 on 2019-10-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0005_auto_20191028_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active'), ('2', 'error')], default='1', max_length=2),
        ),
    ]
