# Generated by Django 2.2.2 on 2019-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0006_auto_20191029_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
