# Generated by Django 2.2.2 on 2019-11-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0007_auto_20191030_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='last_hook_uninstall_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
