# Generated by Django 2.2.2 on 2019-11-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0008_shop_last_hook_uninstall_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscaninfo',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
    ]
