# Generated by Django 2.2.2 on 2019-11-09 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_metadata', '0004_auto_20191109_1112'),
        ('shop', '0009_orderscaninfo_error_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopShippingRateMapping',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('e_commerce_shipping_rate_name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('shipping_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_mappings', to='system_metadata.ShippingRate')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rate_mappings', to='shop.Shop')),
            ],
            options={
                'verbose_name': 'Shop Shipping Rate Mapping',
                'verbose_name_plural': 'Shop Shipping Rate Mappings',
                'db_table': 'shop_shipping_rate_mapping',
            },
        ),
    ]
