# Generated by Django 2.2.2 on 2020-01-04 19:35

import django.contrib.postgres.fields
from django.db import migrations, models

import shop.models.order_scan_info


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0010_shopshippingratemapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderscaninfo',
            options={'verbose_name': 'Order Scan Info', 'verbose_name_plural': 'Order Scan Info'},
        ),
        migrations.RemoveField(
            model_name='orderscaninfo',
            name='last_id',
        ),
        migrations.AddField(
            model_name='orderscaninfo',
            name='checked_order_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='orderscaninfo',
            name='last_order_update_time',
            field=models.DateTimeField(default=shop.models.order_scan_info.default_last_order_update_time),
        ),
    ]
