# Generated by Django 2.2.2 on 2020-01-07 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0011_auto_20200104_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopshippingratemapping',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=list, size=None),
        ),
    ]
