# Generated by Django 2.2.2 on 2020-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0012_shopshippingratemapping_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopshippingratemapping',
            name='hash_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
