# Generated by Django 2.2.2 on 2020-02-19 07:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0013_shopshippingratemapping_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
