# Generated by Django 2.2.2 on 2020-02-19 07:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0014_shop_tsv_metadata_search'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shop',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='shop_tsv_met_348d0a_gin'),
        ),
    ]
