# Generated by Django 2.2.2 on 2020-07-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_shop_create_text_search_trigger_20200219_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopshippingratemapping',
            name='shipping_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_mappings', to='shipping.ShippingRate'),
        ),
    ]
