# Generated by Django 2.2.2 on 2020-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200723_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active'), ('2', 'error')], db_index=True, default='1', max_length=2),
        ),
    ]
