# Generated by Django 2.2.2 on 2020-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200817_1000'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO public.ecommerce (name, description, create_time, update_time) VALUES ('PrintHolo', 'PrintHolo Default Store', current_timestamp, current_timestamp);")
    ]
