# Generated by Django 2.2.2 on 2020-09-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0087_merge_20200925_0813'),
        ('shop', '0019_add_prinholo_ecommerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user_products',
            field=models.ManyToManyField(related_name='shops', through='user_product.ShopUserProduct', to='user_product.UserProduct'),
        ),
    ]
