# Generated by Django 2.2.2 on 2020-10-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_shop_user_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ecommerce_shop_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
