# Generated by Django 2.2.2 on 2020-10-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20201005_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-create_time']},
        ),
    ]
