# Generated by Django 2.2.2 on 2020-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20201012_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active'), ('2', 'error'), ('3', 'new')], db_index=True, default='1', max_length=2),
        ),
    ]
