# Generated by Django 2.2.2 on 2020-10-15 03:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import shop.models.shop


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20201015_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='confirm_installation_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=shop.models.shop.default_confirm_installation_params),
        ),
    ]
