# Generated by Django 2.2.2 on 2020-10-16 06:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0026_auto_20201015_0341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('owner', 'url')},
        ),
    ]
