# Generated by Django 2.2.2 on 2020-10-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_shoptoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderscaninfo',
            name='error_count',
        ),
        migrations.AddField(
            model_name='shop',
            name='api_error_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
