# Generated by Django 2.2.2 on 2020-12-19 04:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20201019_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopShippingProfile',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('profile_id', models.CharField(max_length=100)),
                ('zones_config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_profiles', to='shop.Shop')),
            ],
            options={
                'db_table': 'shop_shipping_profile',
                'ordering': ['-create_time'],
            },
        ),
    ]
