# Generated by Django 2.2.2 on 2021-01-22 06:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_shopshippingprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLocationChange',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('shopify_response', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('new_location', models.BigIntegerField(null=True)),
                ('old_location', models.BigIntegerField(null=True)),
                ('type', models.CharField(choices=[('0', 'not_has_location'), ('1', 'wrong_location')], default='1', max_length=2)),
                ('is_resolve', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_change', to='shop.Shop')),
            ],
            options={
                'db_table': 'shop_location_change',
                'ordering': ['-create_time'],
            },
        ),
    ]
