# Generated by Django 2.2.2 on 2021-04-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_shoplocationchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTag',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='shop.Shop')),
            ],
            options={
                'db_table': 'shop_shop_tag',
                'ordering': ['id'],
            },
        ),
    ]
