# Generated by Django 2.2.2 on 2019-10-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='code',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.RunSQL(
            'UPDATE user_product SET code = 1920476157064370 + id;COMMIT;',
        ),
    ]
