# Generated by Django 2.2.2 on 2019-10-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0002_userproduct_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='code',
            field=models.BigIntegerField(db_index=True, default=0, unique=True),
        ),
    ]
