# Generated by Django 2.2.2 on 2019-10-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0003_auto_20191009_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='thumbnail_url',
            field=models.CharField(default='', max_length=512, verbose_name='Artwork Thumbnail Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uservariantsidemockup',
            name='mockup_thumbnail_url',
            field=models.CharField(default='', max_length=512, verbose_name='Mockup Thumbnail Url'),
            preserve_default=False,
        ),
    ]
