# Generated by Django 2.2.2 on 2019-10-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0006_auto_20191013_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='preview_image_url',
            field=models.TextField(null=True),
        ),
    ]
