# Generated by Django 2.2.2 on 2019-10-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0007_auto_20191013_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='file_url',
        ),
        migrations.AddField(
            model_name='artwork',
            name='original_image_path',
            field=models.TextField(default='', verbose_name='Storage Artwork Path'),
            preserve_default=False,
        ),
    ]
