# Generated by Django 2.2.2 on 2019-10-14 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0008_auto_20191014_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='thumbnail_url',
            new_name='file_url',
        ),
    ]
