# Generated by Django 2.2.2 on 2019-10-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0009_auto_20191014_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='code',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.RunSQL(
            'UPDATE "artwork" SET code = 1920476157064370 + id;COMMIT;',
        ),
    ]
