# Generated by Django 2.2.2 on 2019-10-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0010_artwork_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='code',
            field=models.BigIntegerField(db_index=True, default=0, unique=True),
        ),
    ]
