# Generated by Django 2.2 on 2019-10-24 15:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0011_auto_20191020_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='userproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='user_produc_tsv_met_ffea84_gin'),
        ),
    ]
