# Generated by Django 2.2 on 2019-10-24 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0013_create_text_search_trigger_20191024_1533'),
        ('user_product', '0013_auto_20191024_1456'),
    ]

    operations = [
    ]
