# Generated by Django 2.2.2 on 2019-10-26 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abstract_product', '0008_auto_20191024_1428'),
        ('user_product', '0014_merge_20191024_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAbstractVariantDefaultPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('abstract_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_variant_default_price_set', to='abstract_product.AbstractProductVariant', verbose_name='Abstract Variant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_variant_default_price_set', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Variant Default Price',
                'verbose_name_plural': 'Variant Default Price',
                'db_table': 'user_abstract_variant_default_price',
                'ordering': ['id'],
            },
        ),
    ]
