# Generated by Django 2.2.2 on 2019-10-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0016_update_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='uservariant',
            name='user_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_product_variant_set', to='user_product.UserProduct', verbose_name='User Product'),
        ),
    ]
