# Generated by Django 2.2.2 on 2019-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0017_auto_20191027_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='sort_index',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Index'),
        ),
    ]
