# Generated by Django 2.2.2 on 2019-10-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0018_uservariant_sort_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserproduct',
            name='handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
