# Generated by Django 2.2.2 on 2019-10-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0019_shopuserproduct_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserproduct',
            name='sync_status',
            field=models.CharField(choices=[('0', 'syncing'), ('1', 'synced'), ('2', 'error')], default='1', max_length=1),
        ),
    ]
