# Generated by Django 2.2.2 on 2019-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0020_auto_20191029_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserproduct',
            name='sync_status',
            field=models.CharField(choices=[('0', 'syncing'), ('1', 'synced'), ('2', 'error')], default='0', max_length=1),
        ),
    ]
