# Generated by Django 2.2.2 on 2019-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0021_auto_20191029_1624'),
    ]

    operations = [
        migrations.RunSQL("update shop_user_product set sync_status = '1' where sync_status = 'S';"),
        migrations.RunSQL("update shop_user_product set sync_status = '2' where sync_status = 'E';"),
    ]
