# Generated by Django 2.2.2 on 2019-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0022_update_foreign_key'),
    ]

    operations = [
        migrations.RunSQL("alter table abstract_product_attribute_value alter column attribute_id type bigint using attribute_id::bigint;"),
        migrations.RunSQL("alter table order_cancel_shipping_request_order_packs alter column cancelshippingrequest_id type bigint using cancelshippingrequest_id::bigint;"),
        migrations.RunSQL("alter table order_cancel_shipping_request_order_packs alter column orderpack_id type bigint using orderpack_id::bigint;"),
        migrations.RunSQL("alter table shop_user_product alter column shop_id type bigint using shop_id::bigint;"),
    ]
