# Generated by Django 2.2.2 on 2019-11-08 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0024_auto_20191031_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkHistory',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('original_name', models.CharField(max_length=100, verbose_name='Name')),
                ('original_image_path', models.TextField(verbose_name='Storage Artwork Path')),
                ('sha256', models.CharField(max_length=270)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('original_artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_history_set', to='user_product.Artwork', verbose_name='Origin Artwork')),
            ],
            options={
                'verbose_name': 'Artwork History',
                'verbose_name_plural': 'Artwork Histories',
                'db_table': 'artwork_history',
                'ordering': ['id'],
            },
        ),
    ]
