# Generated by Django 2.2.2 on 2019-11-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0025_artworkhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkhistory',
            name='original_image_path',
        ),
        migrations.AddField(
            model_name='artworkhistory',
            name='original_image_url',
            field=models.TextField(default='', verbose_name='Storage Artwork Url'),
            preserve_default=False,
        ),
    ]
