# Generated by Django 2.2.2 on 2019-11-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0026_auto_20191108_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkhistory',
            options={'ordering': ['-create_time'], 'verbose_name': 'Artwork History', 'verbose_name_plural': 'Artwork Histories'},
        ),
        migrations.AddField(
            model_name='artworkhistory',
            name='original_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artworkhistory',
            name='original_width',
            field=models.IntegerField(default=0),
        ),
    ]
