# Generated by Django 2.2.2 on 2019-11-14 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0027_auto_20191111_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductartwork',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_product_artwork_set', to='user_product.Artwork', verbose_name='Artwork'),
        ),
    ]
