# Generated by Django 2.2 on 2019-11-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0028_auto_20191114_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductartwork',
            name='user_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_set', to='user_product.UserProduct', verbose_name='User Product'),
        ),
    ]
