# Generated by Django 2.2.2 on 2019-12-10 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0029_auto_20191125_0907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservariantsidemockup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='uservariantsidemockup',
            name='product_side',
        ),
    ]
