# Generated by Django 2.2.2 on 2019-12-10 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0029_auto_20191125_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='abstract_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_product_set', to='abstract_product.AbstractProduct', verbose_name='Abstract Product'),
        ),
    ]
