# Generated by Django 2.2.2 on 2019-12-10 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0030_auto_20191210_0433'),
        ('user_product', '0030_auto_20191210_1349'),
    ]

    operations = [
    ]
