# Generated by Django 2.2.2 on 2019-12-23 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0031_merge_20191210_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservariant',
            options={'ordering': ['update_time', 'create_time'], 'verbose_name': 'User Variant', 'verbose_name_plural': 'User Variant'},
        ),
        migrations.AlterModelOptions(
            name='uservariantsidemockup',
            options={'ordering': ['update_time', 'create_time'], 'verbose_name': 'User Variant Side Mockup', 'verbose_name_plural': 'User Variant Side Mockups'},
        ),
    ]
