# Generated by Django 2.2.2 on 2019-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0032_auto_20191223_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='BaseCost'),
        ),
    ]
