# Generated by Django 2.2 on 2019-11-12 08:18

from django.db import migrations

from user_product.models import UserVariant


def update_variant_base_cost(apps, schema_editor):
    for user_variant in UserVariant.objects.all():
        user_variant.base_cost = user_variant.abstract_variant.base_cost
        user_variant.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0033_uservariant_base_cost'),
    ]

    operations = [
        migrations.RunPython(update_variant_base_cost),
    ]
