# Generated by Django 2.2.2 on 2020-01-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0034_update_user_variant_base_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserproduct',
            name='sync_status',
            field=models.CharField(choices=[('0', 'syncing'), ('1', 'synced'), ('2', 'error'), ('3', 'new')], default='3', max_length=1),
        ),
    ]
