# Generated by Django 2.2.2 on 2020-01-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0035_auto_20200103_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
