# Generated by Django 2.2 on 2020-01-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0036_uservariant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='height',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
