# Generated by Django 2.2 on 2020-01-14 06:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0037_auto_20200114_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='artwork_tsv_met_9da33c_gin'),
        ),
    ]
