# Generated by Django 2.2 on 2020-01-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0040_auto_20200114_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
