# Generated by Django 2.2.2 on 2020-01-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0041_auto_20200114_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='thumbnail_image_path',
            field=models.TextField(null=True, verbose_name='Thumbnail Storage Artwork Path'),
        ),
    ]
