# Generated by Django 2.2 on 2019-11-05 15:29
from django.db import migrations

from user_product.models import Artwork


def update_artwork_thumbnail(apps, schema_editor):
    for artwork in Artwork.objects.filter(thumbnail_image_path__isnull=True):
        artwork.thumbnail_image_path = artwork.original_image_path.replace("artworks/originals/", "artworks/thumbnails/")
        artwork.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0042_artwork_thumbnail_image_path'),
    ]

    operations = [
        migrations.RunPython(update_artwork_thumbnail),
    ]
