# Generated by Django 2.2.2 on 2020-02-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0043_update_artwork_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabstractvariantdefaultprice',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
