# Generated by Django 2.2.2 on 2020-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0045_userproduct_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserproduct',
            name='sync_status',
            field=models.CharField(choices=[('0', 'syncing'), ('1', 'synced'), ('2', 'error'), ('3', 'new'), ('4', 'deleted')], default='3', max_length=1),
        ),
    ]
