# Generated by Django 2.2.2 on 2020-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0046_auto_20200221_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
