# Generated by Django 2.2.2 on 2020-03-06 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0029_auto_20200203_1705'),
        ('user_product', '0047_shopuserproduct_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProductArtwork',
            new_name='UserProductArtworkFusion',
        ),
    ]
