# Generated by Django 2.2.2 on 2020-03-06 07:37

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import user_product.constants.artwork_fusion_info_metas


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_product', '0048_auto_20200306_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkFusion',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('original_image_path', models.TextField(verbose_name='Storage Artwork Fusion Path')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Artwork Fusion',
                'verbose_name_plural': 'Artwork Fusions',
                'db_table': 'artwork_fusion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkFusionInfo',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('layer', models.SmallIntegerField(default=1)),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('position', django.contrib.postgres.fields.jsonb.JSONField(default=user_product.constants.artwork_fusion_info_metas.default_position)),
                ('scale', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_fusion_info_frame_set', to='user_product.Artwork', verbose_name='Artwork')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_fusion_info_artwork_set', to='user_product.ArtworkFusion', verbose_name='Artwork Fusion')),
            ],
            options={
                'verbose_name': 'Artwork Fusion Info',
                'verbose_name_plural': 'Artwork Fusion Infos',
                'db_table': 'artwork_fusion_info',
                'ordering': ['id', 'layer'],
            },
        ),
        migrations.AddField(
            model_name='artworkfusion',
            name='artworks',
            field=models.ManyToManyField(through='user_product.ArtworkFusionInfo', to='user_product.Artwork'),
        ),
        migrations.AddField(
            model_name='artworkfusion',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_fusion_set', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
