# Generated by Django 2.2.2 on 2020-03-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0050_auto_20200306_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductartworkfusion',
            name='artwork_fusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_product_artwork_fusion_set', to='user_product.ArtworkFusion', verbose_name='Artwork Fusion'),
        ),
    ]
