# Generated by Django 2.2.2 on 2020-03-06 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0029_auto_20200203_1705'),
        ('user_product', '0051_userproductartworkfusion_artwork_fusion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproductartworkfusion',
            unique_together={('user_product', 'product_side', 'artwork_fusion')},
        ),
        migrations.AlterModelTable(
            name='userproductartworkfusion',
            table='user_product_artwork_fusion',
        )
    ]
