# Generated by Django 2.2 on 2019-11-05 15:29
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0052_auto_20200306_0750'),
    ]

    operations = [
        migrations.RunSQL("UPDATE user_product_artwork_fusion SET artwork_fusion_id = artwork_id;COMMIT;")
    ]
