# Generated by Django 2.2.2 on 2020-03-06 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0029_auto_20200203_1705'),
        ('user_product', '0053_copy_data_artwork_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductartworkfusion',
            name='artwork',
        ),
    ]
