# Generated by Django 2.2.2 on 2020-03-17 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0054_remove_artwork_field_20200306_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductartworkfusion',
            name='framed_artwork_url',
        ),
        migrations.RemoveField(
            model_name='userproductartworkfusion',
            name='meta',
        ),
    ]
