# Generated by Django 2.2.2 on 2020-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0055_auto_20200317_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkfusion',
            name='image_url',
            field=models.TextField(default='', verbose_name='Storage Artwork Fusion Url'),
            preserve_default=False,
        ),
    ]
