# Generated by Django 2.2.2 on 2019-10-26 15:48

from django.db import migrations

from HUB.models.random_id_model import RandomIDModel
from user_product.models import ArtworkFusion, ArtworkFusionInfo


def random_id_artwork_fusion(apps, schema_editor):
    RandomIDModel.init_random_seq(ArtworkFusion)
    RandomIDModel.init_random_seq(ArtworkFusionInfo)


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0056_artworkfusion_image_url'),
    ]

    operations = [
        migrations.RunPython(random_id_artwork_fusion),
    ]
