# Generated by Django 2.2.2 on 2020-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0057_random_id_artwork_fusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkfusion',
            name='image_url',
            field=models.TextField(null=True, verbose_name='Storage Artwork Fusion Url'),
        ),
        migrations.AlterField(
            model_name='artworkfusion',
            name='original_image_path',
            field=models.TextField(null=True, verbose_name='Storage Artwork Fusion Path'),
        ),
    ]
