# Generated by Django 2.2.2 on 2020-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0058_auto_20200325_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkfusioninfo',
            name='dnd_scale',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
    ]
