# Generated by NKT on 2020-07-21 17:53

from django.db import migrations

from HUB.services import gs_image_service
from user_product.models import Artwork


def update_artwork_file_url(apps, schema_editor):
    for artwork in Artwork.objects.exclude(thumbnail_image_path=None):
        artwork.file_url = gs_image_service.get_public_url_from_file_name(artwork.thumbnail_image_path)
        artwork.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0060_ecommerceunsyncedproduct_ecommerceunsyncvariant_uservariantartworkfusion'),
    ]

    operations = [
        migrations.RunPython(update_artwork_file_url),
    ]
