# Generated by Django 2.2.2 on 2020-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0061_migrate_new_googlestorage_image_url_subdomain_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservariant',
            name='base_cost',
        ),
        migrations.AddField(
            model_name='userproduct',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Extra Cost'),
        ),
    ]
