# Generated by Django 2.2.2 on 2020-08-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0062_auto_20200723_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservariantprice',
            name='base_cost',
        ),
    ]
