# Generated by Django 2.2.2 on 2020-08-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0063_remove_uservariantprice_base_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
