# Generated by Django 2.2.2 on 2020-08-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0064_auto_20200805_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
