# Generated by Django 2.2.2 on 2020-08-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0065_auto_20200806_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_active',
        ),
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('0', 'uploaded'), ('1', 'active'), ('3', 'error'), ('2', 'inactive')], db_index=True, default='1', max_length=16),
        ),
    ]
