# Generated by Django 2.2.2 on 2020-08-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0066_auto_20200817_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('4', 'uploaded'), ('1', 'active'), ('3', 'error'), ('2', 'inactive')], db_index=True, default='1', max_length=16),
        ),
    ]
