# Generated by Django 2.2.2 on 2020-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0067_auto_20200817_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='is_refresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopuserproduct',
            name='sync_status',
            field=models.CharField(choices=[('0', 'syncing'), ('1', 'synced'), ('2', 'error'), ('3', 'new'), ('4', 'deleted'), ('5', 'unsyncing')], default='3', max_length=1),
        ),
    ]
