# Generated by Django 2.2.2 on 2020-09-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0068_auto_20200828_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='is_refresh',
        ),
        migrations.AlterField(
            model_name='shopuserproduct',
            name='sync_status',
            field=models.CharField(choices=[('0', 'syncing'), ('1', 'synced'), ('2', 'error'), ('3', 'new'), ('4', 'deleted'), ('5', 'deleting')], default='3', max_length=1),
        ),
    ]
