# Generated by Django 2.2.2 on 2020-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0069_auto_20200901_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserproduct',
            name='is_refresh',
            field=models.BooleanField(default=False),
        ),
    ]
