# Generated by Django 2.2.2 on 2020-09-12 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0070_shopuserproduct_is_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='last_used_time',
            field=models.DateTimeField(default=datetime.date(2020, 9, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='total_created_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('4', 'uploaded'), ('1', 'active'), ('3', 'error'), ('2', 'inactive')], db_index=True, default='4', max_length=16),
        ),
    ]
