# Generated by Django 2.2.2 on 2020-09-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0071_auto_20200912_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkfusion',
            name='artworks',
            field=models.ManyToManyField(related_name='artwork_fusion_set', through='user_product.ArtworkFusionInfo', to='user_product.Artwork'),
        ),
    ]
