# Generated by Django 2.2.2 on 2020-09-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0072_auto_20200912_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserproduct',
            name='sync_status',
            field=models.CharField(choices=[('0', 'syncing'), ('1', 'synced'), ('2', 'error'), ('3', 'new'), ('4', 'deleted'), ('5', 'deleting'), ('6', 'pending_delete')], default='3', max_length=1),
        ),
    ]
