# Generated by Django 2.2.2 on 2020-09-19 10:15

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0043_auto_20200813_1450'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_product', '0073_auto_20200918_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkDefault',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('file_url', models.TextField(verbose_name='Artwork Thumbnail Url')),
                ('original_image_path', models.TextField(verbose_name='Storage Artwork Path')),
                ('thumbnail_image_path', models.TextField(null=True, verbose_name='Thumbnail Storage Artwork Path')),
                ('width', models.IntegerField(db_index=True, default=0)),
                ('height', models.IntegerField(db_index=True, default=0)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('sort_index', models.IntegerField(db_index=True, default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('tsv_metadata_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_default_set', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('product_side_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_default_product_side', to='abstract_product.AbstractProductSide', verbose_name='Abstract Product Side')),
            ],
            options={
                'verbose_name': 'Artwork Default',
                'verbose_name_plural': 'Artworks Default',
                'db_table': 'artwork_',
                'ordering': ['id', 'sort_index'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_default_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_default', to='user_product.ArtworkDefault', verbose_name='Artwork default'),
        ),
        migrations.AddIndex(
            model_name='artworkdefault',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='artwork__tsv_met_83b558_gin'),
        ),
    ]
