# Generated by Django 2.2.2 on 2020-09-19 10:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0074_auto_20200919_1015'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artworkdefault',
            name='artwork__tsv_met_83b558_gin',
        ),
        migrations.AddIndex(
            model_name='artworkdefault',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='artwork_def_tsv_met_7d41d7_gin'),
        ),
        migrations.AlterModelTable(
            name='artworkdefault',
            table='artwork_default',
        ),
    ]
