# Generated by Django 2.2.2 on 2020-09-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0075_auto_20200919_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artwork_default_id',
            new_name='artwork_default',
        ),
        migrations.RenameField(
            model_name='artworkdefault',
            old_name='product_side_id',
            new_name='product_side',
        ),
    ]
