# Generated by Django 2.2.2 on 2020-09-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0076_auto_20200919_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkdefault',
            options={'ordering': ['id'], 'verbose_name': 'Artwork Default', 'verbose_name_plural': 'Artworks Default'},
        ),
        migrations.RemoveField(
            model_name='artworkdefault',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='artworkdefault',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='artworkdefault',
            name='sort_index',
        ),
        migrations.AlterField(
            model_name='artworkdefault',
            name='file_url',
            field=models.TextField(verbose_name='Artwork Default Thumbnail Url'),
        ),
        migrations.AlterField(
            model_name='artworkdefault',
            name='original_image_path',
            field=models.TextField(verbose_name='Storage Artwork Default Path'),
        ),
        migrations.AlterField(
            model_name='artworkdefault',
            name='thumbnail_image_path',
            field=models.TextField(null=True, verbose_name='Thumbnail Storage Artwork Default Path'),
        ),
    ]
