# Generated by Django 2.2.2 on 2020-09-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0043_auto_20200813_1450'),
        ('user_product', '0077_auto_20200920_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_side', to='abstract_product.AbstractProductSide'),
        ),
    ]
