# Generated by Django 2.2.2 on 2020-09-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0078_auto_20200921_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkfusion',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
