# Generated by Django 2.2.2 on 2020-09-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0079_artworkfusion_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='side',
        ),
    ]
