# Generated by Django 2.2.2 on 2020-09-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0079_artworkfusion_background_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservariantprice',
            unique_together={('user_variant', 'currency')},
        ),
    ]
