# Generated by Django 2.2.2 on 2020-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0080_auto_20200924_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkdefault',
            name='last_used_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
