# Generated by Django 2.2.2 on 2020-09-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0081_artworkdefault_last_used_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artworkdefault',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artworkdefault',
            name='sha256',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='artworkdefault',
            name='status',
            field=models.CharField(choices=[('4', 'uploaded'), ('1', 'active'), ('3', 'error'), ('2', 'inactive')], db_index=True, default='4', max_length=16),
        ),
        migrations.AddField(
            model_name='artworkdefault',
            name='total_created_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sha256',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='artworkdefault',
            name='last_used_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
