# Generated by Django 2.2.2 on 2020-09-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0082_auto_20200924_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkdefault',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
