# Generated by Django 2.2.2 on 2020-09-24 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_product', '0083_artworkdefault_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkdefault',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_default_set', to=settings.AUTH_USER_MODEL, verbose_name='Owner Artwork Default'),
        ),
    ]
