# Generated by Django 2.2.2 on 2020-09-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0084_artworkdefault_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkdefault',
            name='status',
            field=models.CharField(choices=[('4', 'uploaded'), ('1', 'active'), ('3', 'error'), ('2', 'inactive')], db_index=True, default='1', max_length=16),
        ),
    ]
