# Generated by Django 2.2.2 on 2020-09-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0085_auto_20200924_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('4', 'uploaded'), ('1', 'active'), ('3', 'error'), ('2', 'inactive'), ('5', 'cloned')], db_index=True, default='4', max_length=16),
        ),
        migrations.AlterField(
            model_name='artworkdefault',
            name='status',
            field=models.CharField(choices=[('4', 'uploaded'), ('1', 'active'), ('3', 'error'), ('2', 'inactive'), ('5', 'cloned')], db_index=True, default='1', max_length=16),
        ),
    ]
