# Generated by Django 2.2.2 on 2020-09-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0080_auto_20200924_1033'),
        ('user_product', '0086_auto_20200925_0606'),
    ]

    operations = [
    ]
