# Generated by Django 2.2.2 on 2020-09-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0088_create_artwork_default_search_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='last_used_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
