# Generated by Django 2.2.2 on 2020-10-24 09:35

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0089_auto_20200929_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProduct',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('preview_image_url', models.TextField(null=True)),
                ('variant_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('detail_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tsv_metadata_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user_product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_product', to='user_product.UserProduct', verbose_name='Sample Product')),
            ],
            options={
                'verbose_name': 'Sample Product',
                'verbose_name_plural': 'Sample Products',
                'db_table': 'sample_product',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='sampleproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='sample_prod_tsv_met_408fad_gin'),
        ),
    ]
