# Generated by Django 2.2.2 on 2020-10-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0091_sample_product_create_text_search_trigger_20201024_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userproduct',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active'), ('2', 'error'), ('3', 'unused')], db_index=True, default='1', max_length=2),
        ),
    ]
