# Generated by Django 2.2.2 on 2020-10-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0092_auto_20201027_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='status',
            field=models.CharField(choices=[('2', 'inactive'), ('1', 'active'), ('4', 'error'), ('3', 'unused')], db_index=True, default='1', max_length=2),
        ),
    ]
