# Generated by Django 2.2.2 on 2020-10-27 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0093_auto_20201027_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleproduct',
            name='user_product',
        ),
        migrations.AddField(
            model_name='sampleproduct',
            name='original_product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sample_product', to='user_product.UserProduct', verbose_name='Sample Product'),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='sample_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_products', to='user_product.SampleProduct', verbose_name='Sample Product'),
        ),
    ]
