# Generated by Django 2.2.2 on 2020-10-27 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0095_auto_20201027_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='sample_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_products', to='user_product.SampleProduct', verbose_name='Original Sample Product'),
        ),
    ]
