# Generated by Django 2.2.2 on 2020-10-27 04:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_product', '0096_auto_20201027_0447'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproduct',
            unique_together={('user', 'sample_product')},
        ),
    ]
