# Generated by Django 2.2.2 on 2020-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0098_remove_sampleproduct_variant_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleproduct',
            name='status',
            field=models.CharField(choices=[('2', 'inactive'), ('1', 'active')], db_index=True, default='1', max_length=2),
        ),
    ]
