# Generated by Django 2.2.2 on 2020-10-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0099_sampleproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkdefault',
            name='product_sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
