# Generated by Django 2.2.2 on 2020-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0101_update_artwork_default_sku_if_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkfusion',
            name='background_color',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
