# Generated by Django 2.2.2 on 2020-11-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0102_auto_20201104_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('4', 'uploaded'), ('1', 'active'), ('3', 'error'), ('2', 'inactive'), ('5', 'cloned'), ('6', 'sample_product_cloned')], db_index=True, default='4', max_length=16),
        ),
        migrations.AlterField(
            model_name='artworkdefault',
            name='status',
            field=models.CharField(choices=[('4', 'uploaded'), ('1', 'active'), ('3', 'error'), ('2', 'inactive'), ('5', 'cloned'), ('6', 'sample_product_cloned')], db_index=True, default='1', max_length=16),
        ),
    ]
