# Generated by Django 2.2.2 on 2020-11-10 03:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0104_auto_20201106_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleproduct',
            name='variant_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
