# Generated by Django 2.2.2 on 2020-11-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0105_sampleproduct_variant_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='sample_product_variant_sku',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Sample Product Variant SKU'),
        ),
    ]
