# Generated by Django 2.2.2 on 2020-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0106_uservariant_sample_product_variant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleproduct',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
