# Generated by Django 2.2.2 on 2020-11-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0109_update_sampleproduct_20201123_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='background_color',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
