# Generated by Django 2.2.2 on 2020-11-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0111_update_sampleproduct_20201124_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_legal_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
