# Generated by Django 2.2.2 on 2020-11-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0112_artwork_is_legal_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='is_legal_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
