# Generated by Django 2.2.2 on 2020-11-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0113_auto_20201124_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkdefault',
            name='is_legal_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
