# Generated by Django 2.2.2 on 2020-11-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0115_update_sampleproduct_20201124_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkfusion',
            name='send_to_fulfill',
            field=models.BooleanField(default=True),
        ),
    ]
