# Generated by Django 2.2.2 on 2020-11-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0116_artworkfusion_send_to_fulfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductartworkfusion',
            name='send_to_fulfill',
            field=models.BooleanField(default=True),
        ),
    ]
