# Generated by Django 2.2.2 on 2020-11-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0117_userproductartworkfusion_send_to_fulfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkfusion',
            name='send_to_fulfill',
        ),
    ]
