# Generated by Django 2.2.2 on 2020-12-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0119_update_sampleproduct_20201204_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkfusion',
            name='last_fusion_update_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
