# Generated by Django 2.2.2 on 2021-01-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0121_userproduct_is_updated_fusions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkfusioninfo',
            options={'ordering': ['layer'], 'verbose_name': 'Artwork Fusion Info', 'verbose_name_plural': 'Artwork Fusion Infos'},
        ),
    ]
