# Generated by Django 2.2.2 on 2021-01-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0122_auto_20210115_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkfusioninfo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
