# Generated by Django 2.2.2 on 2021-01-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0123_artworkfusioninfo_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artworkfusioninfo',
            old_name='visible',
            new_name='is_visible',
        ),
    ]
