# Generated by Django 2.2.2 on 2021-01-26 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_product', '0125_auto_20210122_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFontFamily',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('font_url', models.TextField(null=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='font_family_set', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Font Family',
                'verbose_name_plural': 'User Fonts Family',
                'db_table': 'user_product__user_font_family',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TextPersonalization',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('placeholder_label', models.CharField(blank=True, default='Personal text', max_length=64)),
                ('text', models.CharField(max_length=255)),
                ('text_color', models.CharField(default='#333333', max_length=10, verbose_name='Text Color')),
                ('text_size', models.IntegerField(default=30, verbose_name='Text Size')),
                ('text_spacing', models.IntegerField(default=0, verbose_name='Text Spacing')),
                ('outline_color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Outline Color')),
                ('outline_thickness', models.IntegerField(blank=True, null=True, verbose_name='Outline Thickness')),
                ('shadow_color', models.CharField(blank=True, max_length=10, null=True, verbose_name='Shadow Color')),
                ('shadow_distance', models.IntegerField(blank=True, null=True, verbose_name='Shadow Distance')),
                ('shadow_angle', models.FloatField(blank=True, null=True, verbose_name='Shadow Angle')),
                ('arc', models.IntegerField(default=0, verbose_name='Arc')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('font_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_product.UserFontFamily', verbose_name='Font')),
            ],
            options={
                'verbose_name': 'Text Personalization',
                'verbose_name_plural': 'Texts Personalization',
                'db_table': 'user_product__text_personalization',
                'ordering': ['id'],
            },
        ),
    ]
