# Generated by Django 2.2.2 on 2021-03-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0125_auto_20210122_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='mockup_version',
            field=models.CharField(default='v1', max_length=4),
        ),
    ]
