# Generated by Django 2.2.2 on 2021-03-19 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_product', '0126_userproduct_mockup_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMockup',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('file_url', models.TextField(verbose_name='Artwork Thumbnail Url')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_mockups', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Uploaded Mockup',
                'verbose_name_plural': 'Uploaded Mockups',
                'db_table': 'user_product__uploaded_mockup',
                'ordering': ['-create_time'],
            },
        ),
    ]
