# Generated by Django 2.2.2 on 2021-01-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_product', '0127_random_id_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkfusioninfo',
            name='layer_content_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artworkfusioninfo',
            name='layer_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
