# Generated by Django 2.2.2 on 2020-01-14 14:20
import logging

from django.db import migrations

from HUB.models.random_id_model import RandomIDModel
from user_product.models import UploadedMockup

logger = logging.getLogger(__name__)


def init_random_model(apps, schema_editor):
    RandomIDModel.init_random_seq(UploadedMockup)


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0127_uploadedmockup'),
    ]

    operations = [
        migrations.RunPython(init_random_model),
    ]
