# Generated by Django 2.2.2 on 2021-01-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0129_textpersonalization_is_allow_customize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfontfamily',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
