# Generated by Django 2.2.2 on 2021-02-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0130_auto_20210126_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpersonalization',
            name='raw_svg',
            field=models.TextField(default='<svg version="1.1">/</svg>'),
            preserve_default=False,
        ),
    ]
