# Generated by Django 2.2.2 on 2021-03-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0128_uploaded_mockup_random_id_20210319_1620'),
        ('user_product', '0131_textpersonalization_raw_svg'),
    ]

    operations = [
    ]
