# Generated by Django 2.2.2 on 2021-03-23 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0133_artworkfusioninfo_layer_type'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            UPDATE artwork_fusion_info as a
            SET layer_content_type_id = (SELECT c.id from django_content_type as c WHERE c.model='artwork'), layer_content_id = a.artwork_id
            WHERE a.artwork_id IS NOT NULL
            '''
        ),
    ]
