# Generated by Django 2.2.2 on 2021-03-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0134_layer_content_migration_20210326_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkfusion',
            name='artworks',
        ),
        migrations.RemoveField(
            model_name='artworkfusioninfo',
            name='artwork',
        ),
    ]
