# Generated by Django 2.2.2 on 2020-04-27 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_product', '0135_auto_20210326_0708'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                INSERT INTO public.auth_permission (id, name, content_type_id, codename)
                VALUES (DEFAULT, 'Admin Font Family View', 0, 'admin_font_family_view'),
                       (DEFAULT, 'Admin Font Family Add', 0, 'admin_font_family_add'),
                       (DEFAULT, 'Admin Font Family Update', 0, 'admin_font_family_update'),
                       (DEFAULT, 'Admin Font Family Delete', 0, 'admin_font_family_delete')
            '''
        )
    ]
