# Generated by Django 2.2.2 on 2021-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0136_add_font_family_permission_20210329_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfontfamily',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
