# Generated by Django 2.2.2 on 2021-04-06 07:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0138_sampleproduct_last_refresh_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfontfamily',
            name='available_characters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
