# Generated by Django 2.2.2 on 2021-04-08 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0139_userfontfamily_available_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpersonalization',
            name='font_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_personalization_set', to='user_product.UserFontFamily', verbose_name='Font'),
        ),
    ]
