# Generated by Django 2.2.2 on 2021-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0140_auto_20210408_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpersonalization',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
