# Generated by Django 2.2.2 on 2019-10-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('currency', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Currency Exchange Rate',
                'verbose_name_plural': 'Currency Exchange Rates',
                'db_table': 'system_meta_currency_exchange_rate',
                'ordering': ['currency'],
            },
        ),
    ]
