# Generated by Django 2.2.2 on 2019-10-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyexchangerate',
            name='precision',
            field=models.IntegerField(default=0),
        ),
    ]
