# Generated by Django 2.2.2 on 2019-11-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_metadata', '0002_currencyexchangerate_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rate',
                'db_table': 'system_meta_shipping_rate',
                'ordering': ['name'],
            },
        ),
        migrations.RunSQL("INSERT INTO \"system_meta_shipping_rate\"(\"id\", \"name\", \"slug\", \"description\")"
                          " VALUES "
                          " (1, 'Starter', 'starter', 'Super cheap and super slow'), "
                          " (2, 'Standard', 'standard', 'Normal choice'), "
                          " (3, 'Fast', 'fast', 'Like a rocket')")
    ]
