# Generated by Django 2.2.2 on 2019-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_metadata', '0003_shippingrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['name'], 'verbose_name': 'Shipping Rate', 'verbose_name_plural': 'Shipping Rates'},
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL('UPDATE system_meta_shipping_rate SET "is_default" = true WHERE "id" = 2')
    ]
