# Generated by Django 2.2.2 on 2020-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_metadata', '0005_delete_shippingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('last_updated_content', models.TextField(blank=True, null=True)),
                ('sort_index', models.SmallIntegerField(default=0, verbose_name='Sort Index')),
                ('is_prompt', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'system_meta_policy',
                'ordering': ['sort_index'],
            },
        ),
    ]
