# Generated by Django 2.2.2 on 2020-12-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_metadata', '0006_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
