# Generated by Django 2.2.2 on 2021-04-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_metadata', '0007_policy_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=25, max_digits=32),
        ),
    ]
