# Generated by Django 2.2.2 on 2021-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_metadata', '0008_auto_20210405_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=10, max_digits=32),
        ),
    ]
