# Generated by Django 2.2.2 on 2020-02-21 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='braintree_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_braintree_payment_method',
                'ordering': ['-id'],
            },
        ),
    ]
