# Generated by Django 2.2.2 on 2020-12-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminImageUploaded',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('file_url', models.TextField()),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('path', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'admin_image_uploaded',
                'ordering': ['create_time'],
            },
        ),
    ]
