# Generated by Django 2.2.2 on 2020-12-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminimageuploaded',
            name='path_dir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminimageuploaded',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
