# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('admin_tools', '0004_update_system_setting'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE public.system_setting "
            + "SET value=\'{\"auto_create\": false}\' where type=\'1\' or type=\'2\';"
        ),
    ]
