# Generated by Django 2.2.2 on 2021-02-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0006_update_system_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='type',
            field=models.CharField(choices=[('1', 'auto_send_shipping_order_notification'), ('2', 'auto_send_delivered_order_notification'), ('3', 'ffm_service_setting')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
