# Generated by Django 2.2.2 on 2021-03-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0009_update_system_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_mail', models.CharField(max_length=255)),
                ('is_send_mail_user', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'mail_setting',
            },
        ),
    ]
