# Generated by Django 2.2.2 on 2021-03-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0011_insert_mail_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsetting',
            name='send_order_mail_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
