# Generated by Django 2.2.2 on 2021-03-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0012_mailsetting_send_order_mail_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('app_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mail_sender',
            },
        ),
    ]
