# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('admin_tools', '0014_auto_20210322_0840'),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO public.system_setting (type, name, value, create_time, update_time) VALUES
                    ('5', 'auto_send_review_order', '{\"auto_send\": false,\"send_to_user\": false, \"bcc\": [\"thanhnv@foobla.com\"], \"custom_sender\": {\"email\": \"nguyentuanvu210599@gmail.com\", \"password\": \"gprxwoofhyhpzzcq\"}, \"schedule_start_time\": \"22-03-2021\"}', current_timestamp, current_timestamp), 
                    ('6', 'auto_send_add_payment_notification', '{\"auto_send\": false,\"send_to_user\": false, \"bcc\": [\"thanhnv@foobla.com\"], \"custom_sender\": {\"email\": \"nguyentuanvu210599@gmail.com\", \"password\": \"gprxwoofhyhpzzcq\"}, \"schedule_start_time\": \"22-03-2021\"}', current_timestamp, current_timestamp)
            """
        ),
    ]
