# Generated by Django 2.2.2 on 2019-11-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('admin_tools', '0017_auto_20210420_1047'),
    ]

    operations = [
            migrations.RunSQL(
                """
                    INSERT INTO public.system_setting (type, name, value, create_time, update_time) VALUES
                        ('7', 'schedule_update_tracker', '{\"turn_on_schedule_update_tracker\":true}', current_timestamp, current_timestamp)
                """
            ),
        ]
