# Generated by Django 2.2.2 on 2019-10-05 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPaymentMethod',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('ordinal_number', models.SmallIntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserSettings')),
            ],
            options={
                'db_table': 'billing_general_payment_method',
                'ordering': ['ordinal_number', '-update_time'],
            },
        ),
    ]
