# Generated by Django 2.2.2 on 2019-10-19 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('combine_payment', '0001_initial'),
    ]

    operations = [

    ]
