# Generated by Django 2.2.2 on 2019-10-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('combine_payment', '0002_auto_20191019_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpaymentmethod',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
