# Generated by Django 2.2.2 on 2019-10-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('combine_payment', '0004_auto_20191019_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpaymentmethod',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
