# Generated by Django 2.2.2 on 2020-03-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('combine_payment', '0006_remove_old_paypal_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpaymentmethod',
            name='user_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='user.UserSettings'),
        ),
    ]
