# Generated by Django 2.2.2 on 2019-10-26 15:48

from django.db import migrations

from HUB.models.random_id_model import RandomIDModel
from billing.sub_apps.payoneer_payment.models import UserPayoneerPaymentMethod


def random_id_payoneer_payment(apps, schema_editor):
    RandomIDModel.init_random_seq(UserPayoneerPaymentMethod)


class Migration(migrations.Migration):
    dependencies = [
        ('payoneer_payment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(random_id_payoneer_payment),
    ]
