# Generated by Django 2.2.2 on 2020-02-11 13:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payoneer_payment', '0002_random_id_payoneer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayoneerpaymentmethod',
            name='detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userpayoneerpaymentmethod',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpayoneerpaymentmethod',
            name='type',
            field=models.CharField(blank=True, default='INDIVIDUAL', max_length=100, null=True),
        ),
    ]
