# Generated by Django 2.2.2 on 2020-02-27 09:01

from django.db import migrations
from django.db.models import Count, Max

from billing.sub_apps.payoneer_payment.models import UserPayoneerPaymentMethod


def remove_duplicated_payment_method_with_payer_id(apps, schema_editor):
    duplicated_payment_methods = UserPayoneerPaymentMethod.objects.values("payee_id").order_by().annotate(
        count=Count("payee_id"), max_id=Max("id")).filter(count__gte=2)
    preserved_payment_method_ids = []
    removal_required_payment_method_payee_ids = []
    for payment_method_obj in duplicated_payment_methods:
        preserved_payment_method_ids.append(payment_method_obj.get("max_id"))
        removal_required_payment_method_payee_ids.append(payment_method_obj.get("payee_id"))
    UserPayoneerPaymentMethod.objects.filter(payee_id__in=removal_required_payment_method_payee_ids).exclude(
        id__in=preserved_payment_method_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('payoneer_payment', '0004_auto_20200228_0403'),
    ]

    operations = [
        migrations.RunPython(remove_duplicated_payment_method_with_payer_id),
    ]
