# Generated by Django 2.2.2 on 2020-02-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payoneer_payment', '0005_remove_duplicated_method_with_the_same_payer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayoneerpaymentmethod',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
