# Generated by Django 2.2.2 on 2020-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payoneer_payment', '0006_auto_20200228_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayoneerpaymentmethod',
            name='payee_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
