# Generated by Django 2.2.2 on 2019-10-09 03:01

from django.db import migrations

import user.managers.user


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.user.UserManager()),
            ],
        ),
    ]
