# Generated by Django 2.2.2 on 2019-10-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_auto_20191009_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_change_password',
            field=models.DateTimeField(null=True),
        ),
    ]
