# Generated by Django 2.2.2 on 2019-10-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_user_last_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_send_failed_payment_noti',
            field=models.DateTimeField(null=True),
        ),
    ]
