# Generated by Django 2.2.2 on 2019-12-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_auto_20191024_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='throttling_rate_factor',
            field=models.SmallIntegerField(default=10),
        ),
    ]
