# Generated by Django 2.2.2 on 2019-12-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0006_user_throttling_rate_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('1', 'email'), ('2', 'google')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
