# Generated by Django 2.2.2 on 2020-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0007_auto_20191231_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
