# Generated by Django 2.2.2 on 2020-02-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0009_auto_20200207_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='failed_charge_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
