# Generated by Django 2.2.2 on 2020-02-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0010_auto_20200207_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='Etc/UTC', max_length=50),
        ),
    ]
