# Generated by Django 2.2.2 on 2020-02-11 13:51

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0012_auto_20200211_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='next_charge_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 13, 51, 23, 659762, tzinfo=utc)),
        ),
    ]
