# Generated by Django 2.2.2 on 2020-02-18 03:38

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0013_auto_20200211_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='next_charge_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 3, 38, 5, 687481, tzinfo=utc)),
        ),
    ]
