# Generated by Django 2.2.2 on 2020-02-19 07:33

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0014_auto_20200218_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='next_charge_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 7, 33, 28, 105655, tzinfo=utc)),
        ),
    ]
