# Generated by Django 2.2.2 on 2020-02-19 07:36

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0015_auto_20200219_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='next_charge_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 7, 36, 19, 140149, tzinfo=utc)),
        ),
    ]
