# Generated by Django 2.2.2 on 2020-02-20 09:43

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0017_auto_20200219_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='next_charge_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 9, 43, 37, 392164, tzinfo=utc)),
        ),
    ]
