# Generated by Django 2.2.2 on 2020-02-21 07:47

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0018_auto_20200220_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='next_charge_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 7, 47, 14, 868804, tzinfo=utc)),
        ),
    ]
