# Generated by Django 2.2.2 on 2020-02-21 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0020_auto_20200221_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='next_charge_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
