# Generated by Django 2.2.2 on 2020-02-22 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0021_auto_20200221_0830'),
        ('user', '0020_auto_20200222_1003'),
    ]

    operations = [
    ]
