# Generated by Django 2.2.2 on 2020-03-11 15:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0023_auto_20200227_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='edit_order_items_delay',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
