# Generated by Django 2.2.2 on 2020-03-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0024_usersettings_edit_order_items_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='edit_order_items_delay',
            field=models.DurationField(default=1800),
        ),
    ]
