# Generated by Django 2.2.2 on 2020-03-17 09:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0025_auto_20200311_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='edit_order_items_delay',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
