# Generated by Django 2.2.2 on 2020-04-27 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0027_auto_20200427_1008'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO \"public\".\"django_content_type\" (\"id\", \"app_label\", \"model\") VALUES (0, 'permissions', 'permissions')")
    ]
