# Generated by Django 2.2.2 on 2020-04-27 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0028_auto_20200526_1051'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Abstract Product View', 0, 'admin_abstract_product_view')"
            + ", (DEFAULT, 'Admin Abstract Product Update', 0, 'admin_abstract_product_update')"
            + ", (DEFAULT, 'Admin Product Data Import', 0, 'admin_product_data_import')"
            + ", (DEFAULT, 'Admin Abstract Product Category View', 0, 'admin_abstract_product_category_view')"
            + ", (DEFAULT, 'Admin Abstract Product Category Update', 0, 'admin_abstract_product_category_update')"
            + ", (DEFAULT, 'Admin Transaction View', 0, 'admin_transaction_view')"
            + ", (DEFAULT, 'Admin Refund View', 0, 'admin_refund_view')"
            + ", (DEFAULT, 'Admin Refund Update', 0, 'admin_refund_update')"
            + ", (DEFAULT, 'Admin Mail History View', 0, 'admin_mail_history_view')"
            + ", (DEFAULT, 'Admin Notification Template View', 0, 'admin_notification_template_view')"
            + ", (DEFAULT, 'Admin Notification Template Update', 0, 'admin_notification_template_update')"
            + ", (DEFAULT, 'Admin Order View', 0, 'admin_order_view')"
            + ", (DEFAULT, 'Admin Cancel Shipping View', 0, 'admin_cancel_shipping_view')"
            + ", (DEFAULT, 'Admin Cancel Shipping Update', 0, 'admin_cancel_shipping_update')"
            + ", (DEFAULT, 'Admin Webhook Job View', 0, 'admin_webhook_job_view')"
            + ", (DEFAULT, 'Admin Webhook Job Update', 0, 'admin_webhook_job_update')"
            + ", (DEFAULT, 'Admin User View', 0, 'admin_user_view')"
            + ", (DEFAULT, 'Admin User View', 0, 'admin_user_change_password')"
            + ", (DEFAULT, 'Admin User Change Role', 0, 'admin_user_change_role')"
            + ", (DEFAULT, 'Admin User Login As', 0, 'admin_user_login_as')"
            + ", (DEFAULT, 'Admin Dashboard View', 0, 'admin_dashboard_view')"
        )
    ]
