# Generated by Django 2.2.2 on 2020-04-27 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0029_auto_20200526_1100'),
    ]

    operations = [
        migrations.RunSQL(
            "alter table user_user_permissions alter column user_id type bigint using user_id::bigint;"
        )
    ]
