# Generated by Django 2.2.2 on 2020-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_usersettings_last_create_support_ticket_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_forgot_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_forgot_password_expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
