# Generated by Django 2.2.2 on 2020-08-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20200904_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('user_id', models.BigIntegerField()),
                ('is_revoked', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_token',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['user_id'], name='auth_token_user_id_6ac28c_idx'),
        ),
    ]
