# Generated by Django 2.2.2 on 2020-09-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20200720_0731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlimit',
            unique_together={('view', 'user')},
        ),
    ]
