# Generated by Django 2.2.2 on 2020-09-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20200904_0823'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Order Invalid View', 0, 'admin_order_invalid_view')"
        )
    ]
