# Generated by Django 2.2.2 on 2020-08-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20200809_0734'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='authtoken',
        #     name='create_time',
        #     field=models.DateTimeField(auto_now_add=True),
        # ),
        migrations.AlterField(
            model_name='authtoken',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
