# Generated by Django 2.2.2 on 2020-09-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20200809_0742'),
        ('user', '0034_auto_20200914_1435'),
    ]

    operations = [
    ]
