# Generated by Django 2.2.2 on 2020-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_merge_20200917_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(max_length=256),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['token'], name='auth_token_token_da966a_idx'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['is_revoked'], name='auth_token_is_revo_e6f87d_idx'),
        ),
    ]
