# Generated by Django 2.2.2 on 2020-09-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20200917_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='tracking_generation_time',
            field=models.CharField(default=('after_pushed',), max_length=20),
        ),
    ]
