# Generated by Django 2.2.2 on 2020-10-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_usersettings_tracking_generation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='tracking_generation_time',
        ),
    ]
