# Generated by Django 2.2.2 on 2020-10-01 09:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_remove_usersettings_tracking_generation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='tracking_generation_time',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
