# Generated by Django 2.2.2 on 2020-10-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_remove_usersettings_tracking_generation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='tracking_generation_time',
            field=models.IntegerField(default=-3),
        ),
    ]
