# Generated by Django 2.2.2 on 2020-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_usersettings_tracking_generation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('1', 'email'), ('2', 'google'), ('3', 'shopify')], default='1', max_length=2),
        ),
    ]
