# Generated by Django 2.2.2 on 2020-10-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20201012_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='last_used_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='type',
            field=models.CharField(choices=[('1', 'web'), ('2', 'shopify')], default='1', max_length=2),
        ),
    ]
