# Generated by Django 2.2.2 on 2020-10-20 04:40

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20201013_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='user_tsv_met_3c1540_gin'),
        ),
    ]
