# Generated by Django 2.2.2 on 2020-09-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_user_text_search_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Order Holding View', 0, 'admin_order_holding_view')"
        )
    ]
