# Generated by Django 2.2.2 on 2020-10-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_add_permission_user_order_holding'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Statistic Update', 0, 'admin_statistic_update')"
        )
    ]
