# Generated by Django 2.2.2 on 2020-10-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_add_permission_user_update_statistic'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Artwork Default Modify', 0, 'admin_artwork_default_modify')"
        )
    ]
