# Generated by Django 2.2.2 on 2020-10-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_add_permission_user_modify_artwork_default'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Coupon View', 0, 'admin_coupon_view')"
            + ", (DEFAULT, 'Admin Campaign Coupon View', 0, 'admin_coupon_campaign_view')"
        )
    ]
