# Generated by Django 2.2.2 on 2020-12-02 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_20201202_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='request_order_processing_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='edit_order_items_delay',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
