# Generated by Django 2.2.2 on 2020-09-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_update_user_instant_prompt_20201203_0911'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Update User', 0, 'admin_update_user')"
        )
    ]
