# Generated by Django 2.2.2 on 2020-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_update_user_instant_prompt_20201203_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
