# Generated by Django 2.2.2 on 2020-12-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_user_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='request_order_processing_manually',
            field=models.BooleanField(default=True),
        ),
    ]
