# Generated by Django 2.2.2 on 2020-12-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_auto_20201203_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='request_order_processing_manually',
            field=models.BooleanField(default=False),
        ),
    ]
