# Generated by Django 2.2.2 on 2020-12-02 08:13
from django.contrib.auth import get_user_model
from django.db import migrations

from notification.enums.instant_prompt_types import InstantPromptType
from notification.enums.message_statuses import MessageStatus
from notification.models import InstantPrompt

User = get_user_model()


def update_order_processing_time_instant_prompt(apps, schema_editor):
    instant_prompt_to_create = []
    for user in User.objects.all():
        user_order_instant_prompts = InstantPrompt.objects.filter(owner=user,
                                                                  type=InstantPromptType.ORDER_PROCESSING_TIME)
        if len(user_order_instant_prompts) == 0:
            instant_prompt_to_create.append(
                InstantPrompt(owner=user, type=InstantPromptType.ORDER_PROCESSING_TIME, status=MessageStatus.UNREAD))

    InstantPrompt.objects.bulk_create(instant_prompt_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0056_auto_20201204_0632'),
    ]

    operations = [
        migrations.RunPython(update_order_processing_time_instant_prompt),
    ]
