# Generated by Django 2.2.2 on 2020-12-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_add_permission_admin_update_user'),
        ('user', '0057_update_user_instant_prompt_20201203_0911'),
    ]

    operations = [
    ]
