# Generated by Django 2.2.2 on 2020-04-27 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0058_merge_20201207_1703'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Instant Prompt View', 0, 'admin_instant_prompt_view')"
            + ", (DEFAULT, 'Admin Instant Prompt Create', 0, 'admin_instant_prompt_create')"
            + ", (DEFAULT, 'Admin Instant Prompt Update', 0, 'admin_instant_prompt_update')"
        )
    ]
