# Generated by Django 2.2.2 on 2020-04-27 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0059_auto_20201208_1357'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Policy View', 0, 'admin_policy_view')"
            + ", (DEFAULT, 'Admin Policy Create', 0, 'admin_policy_create')"
            + ", (DEFAULT, 'Admin Policy Update', 0, 'admin_policy_update')"
        )
    ]
