# Generated by Django 2.2.2 on 2020-12-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_add_policy_permission_20201210_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
