# Generated by Django 2.2.2 on 2020-12-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_add_permission_admin_shop_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='tracking_generation_time',
            field=models.IntegerField(default=-1),
        ),
    ]
