# Generated by Django 2.2.2 on 2021-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_add_highlight_product_permission_20210105_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
