# Generated by Django 2.2.2 on 2020-04-27 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0065_add_highlight_product_permission_20210105_1604'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO \"public\".\"auth_permission\" (\"id\", \"name\", \"content_type_id\", \"codename\") VALUES (DEFAULT, 'Admin Sample Background Add', 0, 'admin_sample_product_add')"
            + ", (DEFAULT, 'Admin Sample Background Delete', 0, 'admin_sample_product_delete')"
        )
    ]
