# Generated by Django 2.2.2 on 2021-03-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_auto_20210222_1008'),
        ('user', '0066_add_sample_background_permission_20210223_0934'),
    ]

    operations = [
    ]
