# Generated by Django 2.2.2 on 2021-03-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_merge_20210302_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
