# Generated by Django 2.2.2 on 2021-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='default_branding_card_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
