# Generated by Django 2.2.2 on 2021-04-16 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20210416_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_branding_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_product.UserVariant'),
        ),
    ]
