# Generated by Django 2.2.2 on 2019-10-05 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractproductvariant',
            name='description',
        ),
    ]
