# Generated by Django 2.2.2 on 2019-10-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0002_remove_abstractproductvariant_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='abstractproductvariantattribute',
            index=models.Index(fields=['variant', 'attribute_value'], name='abstract_pr_variant_0f9eb7_idx'),
        ),
    ]
