# Generated by Django 2.2.2 on 2019-10-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0003_auto_20191009_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsideimages',
            name='preview_image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
