# Generated by Django 2.2.2 on 2019-10-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0004_auto_20191017_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductvariant',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
