# Generated by Django 2.2.2 on 2019-10-17 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0005_abstractproductvariant_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abstractproductvariant',
            unique_together={('product', 'title', 'sku')},
        ),
    ]
