# Generated by Django 2.2.2 on 2019-10-17 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0006_auto_20191017_1704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abstractproductvariant',
            unique_together=set(),
        ),
    ]
