# Generated by Django 2.2.2 on 2019-10-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0008_auto_20191024_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='sort_index',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Index'),
        ),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 0 WHERE \"value\" = 'xs'"),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 1 WHERE \"value\" = 's'"),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 2 WHERE \"value\" = 'm'"),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 3 WHERE \"value\" = 'l'"),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 4 WHERE \"value\" = 'xl'"),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 5 WHERE \"value\" = '2xl'"),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 6 WHERE \"value\" = '3xl'"),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 7 WHERE \"value\" = '4xl'"),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 8 WHERE \"value\" = '5xl'"),
        migrations.RunSQL("UPDATE abstract_product_attribute_value SET sort_index = 9 WHERE \"value\" = '6xl'")
    ]
