# Generated by Django 2.2.2 on 2019-11-14 08:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import abstract_product.models.abstract_product_side


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0009_productattributevalue_sort_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductside',
            name='constraints',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=abstract_product.models.abstract_product_side.default_constraints),
        ),
    ]
