# Generated by Django 2.2.2 on 2019-11-14 08:51

from django.db import migrations


def migrate_update_abstract_product_constraints(apps, schema_editor):
    AbstractProductSide = apps.get_model("abstract_product", "AbstractProductSide")
    AbstractProductSide.objects.filter(abstract_product__title__in=["Classic Men's T-Shirt",
                                                                    "Youth Classic Tee",
                                                                    "Classic Women's T-Shirt",
                                                                    "Unisex Sweatshirt",
                                                                    "Women's V-Neck T-Shirt",
                                                                    "Unisex Hoodie",
                                                                    "Women's Tank Top",
                                                                    "Men's Tank Top",
                                                                    "Unisex Long Sleeve T-Shirt",
                                                                    "Men V-Neck Tshirt",
                                                                    "Black Mug",
                                                                    "White Mug", ]) \
        .update(constraints={"minimum_dpi": 300, "allowed_sizes": [{"width": 4500, "height": 5400},
                                                                   {"width": 2400, "height": 3000},
                                                                   {"width": 2100, "height": 2400},
                                                                   {"width": 2400, "height": 3200},
                                                                   {"width": 4200, "height": 4800}]})
    AbstractProductSide.objects.filter(abstract_product__title__in=["Poster Vertical"]) \
        .update(constraints={"minimum_dpi": 300, "allowed_sizes": [{"width": 2400, "height": 3600}]})
    AbstractProductSide.objects.filter(abstract_product__title__in=["Poster Horizontal"]) \
        .update(constraints={"minimum_dpi": 300, "allowed_sizes": [{"width": 3600, "height": 2400}]})
    AbstractProductSide.objects.filter(abstract_product__title__in=["Poster Square"]) \
        .update(constraints={"minimum_dpi": 300, "allowed_sizes": [{"width": 3000, "height": 3000}]})
    AbstractProductSide.objects.filter(abstract_product__title__in=["Quilt"]) \
        .update(constraints={"minimum_dpi": 300, "allowed_sizes": [{"width": 5000, "height": 5500}]})


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0010_abstractproductside_constraints'),
    ]

    operations = [
        migrations.RunPython(migrate_update_abstract_product_constraints),
    ]
