# Generated by Django 2.2.2 on 2019-11-21 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0011_update_abstractproductside_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractProductMockupInfo',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('abstract_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockup_infos', to='abstract_product.AbstractProduct')),
            ],
            options={
                'verbose_name': 'Abstract Product Mockup Info',
                'verbose_name_plural': 'Abstract Product Mockup Info',
                'db_table': 'abstract_product_mockup_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AbstractVariantSideMockupInfo',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('mockup_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_sides', to='abstract_product.AbstractProductMockupInfo')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_mockup_infos', to='abstract_product.AbstractProductSide')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_mockup_infos', to='abstract_product.AbstractProductVariant')),
            ],
            options={
                'verbose_name': 'Abstract Variant Side Mockup Info',
                'verbose_name_plural': 'Abstract Variant Side Mockup Infos',
                'db_table': 'abstract_variant_side_mockup_info',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='ProductSideImages',
        ),
        migrations.AddIndex(
            model_name='abstractvariantsidemockupinfo',
            index=models.Index(fields=['variant', 'side'], name='abstract_va_variant_7cb004_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='abstractvariantsidemockupinfo',
            unique_together={('variant', 'side')},
        ),
    ]
