# Generated by Django 2.2.2 on 2019-11-21 09:45

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import abstract_product.models.abstract_product_mockup_info


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0012_auto_20191121_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductmockupinfo',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=abstract_product.models.abstract_product_mockup_info.default_meta),
        ),
        migrations.AlterField(
            model_name='abstractproductside',
            name='abstract_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='abstract_product.AbstractProduct'),
        ),
    ]
