# Generated by Django 2.2 on 2019-11-05 15:29
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0014_auto_20191121_0952'),
    ]

    operations = [
        # migrations.RunPython(sync_abstract_product),
    ]
