# Generated by Django 2.2.2 on 2019-12-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0015_update_abstract_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['sort_index', 'name'], 'verbose_name': 'Product Attribute', 'verbose_name_plural': 'Product Attributes'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'ordering': ['attribute__sort_index', 'attribute__name'], 'verbose_name': 'Product Attribute Value', 'verbose_name_plural': 'Product Attribute Values'},
        ),
        migrations.AddField(
            model_name='productattribute',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
    ]
