# Generated by Django 2.2.2 on 2019-12-10 13:49

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import abstract_product.models.abstract_product_mockup_info


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0015_update_abstract_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductmockupinfo',
            name='preview',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=abstract_product.models.abstract_product_mockup_info.default_preview),
        ),
        migrations.AddField(
            model_name='abstractproductvariant',
            name='mockup_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='abstract_product.AbstractProductMockupInfo', verbose_name='Mockup Info'),
        ),
        migrations.DeleteModel(
            name='AbstractVariantSideMockupInfo',
        ),
    ]
