# Generated by Django 2.2.2 on 2019-12-10 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0016_auto_20191210_1349'),
        ('abstract_product', '0016_auto_20191210_0433'),
    ]

    operations = [
    ]
