# Generated by Django 2.2.2 on 2019-12-23 09:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import abstract_product.models.abstract_product_meta


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0020_update_abstract_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractproductmeta',
            name='frame_height',
        ),
        migrations.RemoveField(
            model_name='abstractproductmeta',
            name='frame_width',
        ),
        migrations.RemoveField(
            model_name='abstractproductmeta',
            name='offset_height',
        ),
        migrations.RemoveField(
            model_name='abstractproductmeta',
            name='offset_width',
        ),
        migrations.RemoveField(
            model_name='abstractproductvariant',
            name='currency',
        ),
        migrations.AddField(
            model_name='abstractproductmeta',
            name='pricing_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=abstract_product.models.abstract_product_meta.default_pricing_meta),
        ),
    ]
