# Generated by Django 2.2.2 on 2019-12-23 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0021_auto_20191223_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractproductmeta',
            name='currency',
        ),
    ]
