# Generated by Django 2.2.2 on 2019-12-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0022_remove_abstractproductmeta_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
