# Generated by Django 2.2.2 on 2019-12-25 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0023_auto_20191225_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractproductcategory',
            name='description',
        ),
    ]
