# Generated by Django 2.2 on 2019-11-05 15:29
from django.db import migrations

# from data_import import sync_abstract_product


def sync_product(apps, schema_editor):
    # sync_abstract_product(update=False)
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0024_remove_abstractproductcategory_description'),
    ]

    operations = [
        migrations.RunPython(sync_product),
    ]
