# Generated by Django 2.2.2 on 2020-01-13 13:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import abstract_product.models.abstract_product_meta


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0025_update_abstract_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductmeta',
            name='shipping_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=abstract_product.models.abstract_product_meta.default_shipping_meta),
        ),
        migrations.AddField(
            model_name='abstractproductmeta',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short Description'),
        ),
    ]
