# Generated by Django 2.2.2 on 2020-02-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0027_auto_20200114_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductmockupinfo',
            name='enable_preview',
            field=models.BooleanField(default=False),
        ),
    ]
