# Generated by Django 2.2.2 on 2020-02-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0028_abstractproductmockupinfo_enable_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractproduct',
            options={'ordering': ['sort_index', 'id'], 'verbose_name': 'Abstract Product', 'verbose_name_plural': 'Abstract Products'},
        ),
        migrations.AddField(
            model_name='abstractproduct',
            name='sort_index',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Index'),
        ),
    ]
