# Generated by Django 2.2.2 on 2020-03-17 11:38

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0029_auto_20200203_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproduct',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
