# Generated by Django 2.2.2 on 2020-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0031_update_title_and categories_in_text_search_20200317_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductside',
            name='artwork_fusion_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractproductside',
            name='artwork_fusion_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
