# Generated by Django 2.2.2 on 2020-03-20 04:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import abstract_product.models.abstract_product_side


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0032_auto_20200319_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractproductside',
            name='artwork_fusion_height',
        ),
        migrations.RemoveField(
            model_name='abstractproductside',
            name='artwork_fusion_width',
        ),
        migrations.AddField(
            model_name='abstractproductside',
            name='fusion_size',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=abstract_product.models.abstract_product_side.default_fusion_size),
        ),
    ]
