# Generated by Django 2.2.2 on 2020-05-05 03:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0033_auto_20200320_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductmockupinfo',
            name='preview_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=({'enable_preview': True, 'zIndex': 3},)),
        ),
    ]
