# Generated by Django 2.2.2 on 2020-05-05 04:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0034_abstractproductmockupinfo_preview_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractproductmockupinfo',
            name='preview_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=({'enable_preview': True, 'z_index': 3},)),
        ),
    ]
