# Generated by Django 2.2.2 on 2020-07-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0036_remove_abstractproductmockupinfo_enable_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductmeta',
            name='use_artwork',
            field=models.BooleanField(default=True),
        ),
    ]
