# Generated by Django 2.2.2 on 2020-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0038_remove_abstractproductmeta_use_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductvariant',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Additional Cost'),
        ),
        migrations.AddField(
            model_name='abstractproductvariant',
            name='fulfill_additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Fulfill Additional Cost'),
        ),
        migrations.AddField(
            model_name='abstractproductvariant',
            name='fulfill_base_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Fulfill Base Cost'),
        ),
        migrations.AlterField(
            model_name='abstractproductvariant',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Base Cost'),
        ),
    ]
