# Generated by Django 2.2.2 on 2020-07-29 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0039_auto_20200723_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractproductside',
            name='abstract_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='abstract_product.AbstractProduct'),
        ),
    ]
