# Generated by Django 2.2.2 on 2020-08-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0040_auto_20200729_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproduct',
            name='sku',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
