# Generated by Django 2.2.2 on 2020-08-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0041_abstractproduct_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
