# Generated by Django 2.2.2 on 2020-08-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0042_abstractproductvariant_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='select_type',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='type',
            field=models.CharField(default='size', max_length=31, verbose_name='Select Type'),
            preserve_default=False,
        ),
    ]
