# Generated by Django 2.2.2 on 2020-09-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0043_auto_20200813_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractproductcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Title'),
        ),
    ]
