# Generated by Django 2.2.2 on 2020-09-29 08:25

import abstract_product.models.abstract_product_meta
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0044_auto_20200925_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductmeta',
            name='template_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=abstract_product.models.abstract_product_meta.default_template_meta),
        ),
    ]
