# Generated by Django 2.2.2 on 2020-10-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0046_auto_20201002_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductside',
            name='enable_background_color',
            field=models.BooleanField(default=False),
        ),
    ]
