# Generated by Django 2.2.2 on 2020-11-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0047_abstractproductside_enable_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductside',
            name='fulfill_require_artwork',
            field=models.BooleanField(default=True),
        ),
    ]
