# Generated by Django 2.2.2 on 2020-11-05 07:12

import abstract_product.models.abstract_product_meta
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0048_abstractproductside_fulfill_require_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductmeta',
            name='fusion_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=abstract_product.models.abstract_product_meta.default_fusion_meta),
        ),
    ]
