# Generated by Django 2.2.2 on 2020-11-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0049_abstractproductmeta_fusion_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductcategory',
            name='force_active',
            field=models.BooleanField(default=False),
        ),
    ]
