# Generated by Django 2.2.2 on 2020-11-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0050_abstractproductcategory_force_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractproduct',
            name='sku',
            field=models.CharField(max_length=255, null=True, verbose_name='SKU'),
        ),
    ]
