# Generated by Django 2.2.2 on 2020-12-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0051_auto_20201119_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproductmeta',
            name='artwork_note',
            field=models.TextField(null=True),
        ),
    ]
