# Generated by Django 2.2.2 on 2020-12-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0052_abstractproductmeta_artwork_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractproductmeta',
            old_name='artwork_note',
            new_name='design_note',
        ),
    ]
