# Generated by Django 2.2.2 on 2021-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0053_abstract_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproduct',
            name='is_catalog_visible',
            field=models.BooleanField(default=True),
        ),
    ]
