# Generated by Django 2.2.2 on 2021-02-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0054_abstractproduct_is_catalog_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFMProductInfo',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('supplier', models.CharField(max_length=50)),
                ('ph_product_sku', models.CharField(max_length=255, null=True)),
                ('supplier_product_sku', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
