# Generated by Django 2.2.2 on 2021-03-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0055_ffmproductinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ffmproductinfo',
            table='ffm_product_info',
        ),
    ]
