# Generated by Django 2.2.2 on 2021-03-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0056_auto_20210301_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproduct',
            name='active_mockup_version',
            field=models.CharField(default='v1', max_length=4),
        ),
    ]
