# Generated by Django 2.2.2 on 2021-03-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0057_abstractproduct_active_mockup_version'),
    ]

    operations = [
        migrations.RunSQL(
            "update public.ffm_product_info set supplier = '1' where supplier = 'Fulfillment';"
        ),
        migrations.AlterField(
            model_name='ffmproductinfo',
            name='supplier',
            field=models.CharField(choices=[('1', 'fulfillment')], max_length=1),
        ),
    ]
