# Generated by Django 2.2.2 on 2021-04-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0058_auto_20210325_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffmproductinfo',
            name='ph_product_sku',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ffmproductinfo',
            name='supplier_product_sku',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
