# Generated by Django 2.2.2 on 2021-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0059_auto_20210405_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUTemplate',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='SKU')),
                ('png_template_url', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SKU Template',
                'verbose_name_plural': 'SKU Templates',
                'db_table': 'abstract_product__sku_template',
                'ordering': ['sku'],
            },
        ),
    ]
