# Generated by Django 2.2.2 on 2021-04-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0060_skutemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproduct',
            name='type',
            field=models.CharField(choices=[('1', 'aop_product'), ('2', 'flat_product'), ('3', 'branding_card')], default='2', max_length=2),
        ),
    ]
