# Generated by Django 2.2.2 on 2021-04-15 03:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abstract_product', '0061_abstractproduct_type'),
    ]

    operations = [
        migrations.RunSQL('''
            UPDATE public.abstract_product as ab SET type = '1'
            WHERE ab.id in (SELECT DISTINCT abmf.abstract_product_id
            FROM public.abstract_product_mockup_info as abmf
            WHERE meta::text like '%.npy%');
        ''')
    ]

