# Generated by Django 2.2.2 on 2021-04-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0062_update_abstract_type_20210415_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractproduct',
            name='type',
            field=models.CharField(choices=[('1', 'aop_product'), ('2', 'flat_product'), ('3', 'thank_you_card')], default='2', max_length=2),
        ),
    ]
