# Generated by Django 2.2.2 on 2020-04-30 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalVaultPaymentMethod',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('card_name', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.CharField(db_index=True, max_length=30)),
                ('last4', models.CharField(max_length=5)),
                ('exp_month', models.CharField(max_length=5)),
                ('exp_year', models.CharField(max_length=5)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_vault_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_paypal_vault_payment_method',
                'ordering': ['-id'],
            },
        ),
    ]
