# Generated by Django 2.2.2 on 2020-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_vault_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalvaultpaymentmethod',
            name='payment_token',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
