# Generated by Django 2.2.2 on 2019-10-26 15:48

from django.db import migrations

from HUB.models.random_id_model import RandomIDModel
from billing.sub_apps.paypal_vault_payment.models import PaypalVaultPaymentMethod


def random_id_paypal_method(apps, schema_editor):
    RandomIDModel.init_random_seq(PaypalVaultPaymentMethod)


class Migration(migrations.Migration):
    dependencies = [
        ('paypal_vault_payment', '0002_paypalvaultpaymentmethod_payment_token'),
    ]

    operations = [
        migrations.RunPython(random_id_paypal_method),
    ]
