# Generated by Django 2.2.2 on 2020-07-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('abstract_product', '0039_auto_20200723_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=31)),
                ('slug', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=1023)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shipping_rate',
                'ordering': ['update_time', 'create_time'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=1023)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shipping_zone',
                'ordering': ['update_time', 'create_time'],
            },
        ),
        migrations.CreateModel(
            name='ShippingPriceAbstractVariant',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fulfill_base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fulfill_additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('shipping_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingRate')),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingZone')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstract_product.AbstractProductVariant')),
            ],
            options={
                'db_table': 'shipping_price_abstract_variant',
                'ordering': ['update_time', 'create_time'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=31)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('zones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingZone')),
            ],
            options={
                'db_table': 'shipping_country',
                'ordering': ['update_time', 'create_time'],
            },
        ),

        migrations.RunSQL("INSERT INTO public.shipping_rate (id, code, slug, description, update_time, create_time) VALUES (1, 'standard', 'standard', 'Standard Shipping', '2020-07-23 20:39:11.466000', '2020-07-23 20:39:12.553000')"),
        migrations.RunSQL("UPDATE shop_shipping_rate_mapping SET shipping_rate_id = 1 WHERE 1 = 1"),
        migrations.RunSQL("UPDATE public.order SET shipping_rate_id = 1 WHERE 1 = 1"),
        migrations.RunSQL("INSERT INTO public.shipping_zone (id, name, description, update_time, create_time) VALUES (1, 'US', 'United States', current_timestamp, current_timestamp)"),
        migrations.RunSQL("INSERT INTO public.shipping_zone (id, name, description, update_time, create_time) VALUES (2, 'ROW', 'Rest Of The World', current_timestamp, current_timestamp)"),
        migrations.RunSQL("INSERT INTO public.shipping_country (id, code, name, update_time, create_time, zones_id) "
                          + "VALUES (DEFAULT, 'AF', 'Afghanistan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AL', 'Albania', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'DZ', 'Algeria', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AS', 'American Samoa', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AD', 'Andorra', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AO', 'Angola', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AI', 'Anguilla', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AQ', 'Antarctica', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AG', 'Antigua and Barbuda', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AR', 'Argentina', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AM', 'Armenia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AW', 'Aruba', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AU', 'Australia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AT', 'Austria', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AZ', 'Azerbaijan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BS', 'Bahamas', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BH', 'Bahrain', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BD', 'Bangladesh', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BB', 'Barbados', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BY', 'Belarus', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BE', 'Belgium', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BZ', 'Belize', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BJ', 'Benin', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BM', 'Bermuda', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BT', 'Bhutan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BO', 'Bolivia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BQ', 'Bonaire', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BA', 'Bosnia and Herzegovina', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BW', 'Botswana', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BV', 'Bouvet Island', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BR', 'Brazil', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'IO', 'British Territory', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BN', 'Brunei Darussalam', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BG', 'Bulgaria', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BF', 'Burkina Faso', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BI', 'Burundi', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KH', 'Cambodia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CM', 'Cameroon', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CA', 'Canada', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CV', 'Cape Verde', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KY', 'Cayman Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CF', 'Central African Republic', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TD', 'Chad', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CL', 'Chile', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CN', 'China', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CX', 'Christmas Island', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CC', 'Cocos (Keeling) Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CO', 'Colombia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KM', 'Comoros', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CG', 'Congo', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CD', 'Congo', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CK', 'Cook Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CR', 'Costa Rica', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CI', 'Ivory Coast', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'HR', 'Croatia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CU', 'Cuba', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CW', 'Cura√ßao', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CY', 'Cyprus', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CZ', 'Czech Republic', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'DK', 'Denmark', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'DJ', 'Djibouti', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'DM', 'Dominica', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'DO', 'Dominican Republic', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'EC', 'Ecuador', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'EG', 'Egypt', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SV', 'El Salvador', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GQ', 'Equatorial Guinea', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ER', 'Eritrea', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'EE', 'Estonia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ET', 'Ethiopia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'FK', 'Falkland Islands (Malvinas)', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'FO', 'Faroe Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'FJ', 'Fiji', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'FI', 'Finland', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'FR', 'France', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GF', 'French Guiana', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PF', 'French Polynesia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TF', 'French Southern Territories', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GA', 'Gabon', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GM', 'Gambia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GE', 'Georgia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'DE', 'Germany', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GH', 'Ghana', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GI', 'Gibraltar', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GR', 'Greece', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GL', 'Greenland', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GD', 'Grenada', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GP', 'Guadeloupe', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GU', 'Guam', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GT', 'Guatemala', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GG', 'Guernsey', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GN', 'Guinea', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GW', 'Guinea-Bissau', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GY', 'Guyana', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'HT', 'Haiti', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'HM', 'Heard/McDonald Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'VA', 'Holy See', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'HN', 'Honduras', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'HK', 'Hong Kong', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'HU', 'Hungary', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'IS', 'Iceland', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'IN', 'India', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ID', 'Indonesia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'IR', 'Iran', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'IQ', 'Iraq', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'IE', 'Ireland', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'IM', 'Isle of Man', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'IL', 'Israel', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'IT', 'Italy', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'JM', 'Jamaica', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'JP', 'Japan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'JE', 'Jersey', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'JO', 'Jordan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KZ', 'Kazakhstan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KE', 'Kenya', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KI', 'Kiribati', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KP', 'Korea', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KR', 'Korea', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KW', 'Kuwait', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KG', 'Kyrgyzstan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LA', 'Lao', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LV', 'Latvia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LB', 'Lebanon', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LS', 'Lesotho', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LR', 'Liberia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LY', 'Libya', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LI', 'Liechtenstein', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LT', 'Lithuania', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LU', 'Luxembourg', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MO', 'Macao', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MK', 'Macedonia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MG', 'Madagascar', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MW', 'Malawi', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MY', 'Malaysia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MV', 'Maldives', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ML', 'Mali', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MT', 'Malta', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MH', 'Marshall Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MQ', 'Martinique', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MR', 'Mauritania', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MU', 'Mauritius', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'YT', 'Mayotte', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MX', 'Mexico', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'FM', 'Micronesia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MD', 'Moldova', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MC', 'Monaco', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MN', 'Mongolia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ME', 'Montenegro', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MS', 'Montserrat', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MA', 'Morocco', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MZ', 'Mozambique', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MM', 'Myanmar', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NA', 'Namibia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NR', 'Nauru', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NP', 'Nepal', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NL', 'Netherlands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NC', 'New Caledonia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NZ', 'New Zealand', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NI', 'Nicaragua', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NE', 'Niger', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NG', 'Nigeria', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NU', 'Niue', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NF', 'Norfolk Island', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MP', 'Northern Mariana Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'NO', 'Norway', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'OM', 'Oman', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PK', 'Pakistan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PW', 'Palau', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PS', 'Palestine, State of', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PA', 'Panama', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PG', 'Papua New Guinea', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PY', 'Paraguay', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PE', 'Peru', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PH', 'Philippines', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PN', 'Pitcairn', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PL', 'Poland', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PT', 'Portugal', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PR', 'Puerto Rico', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'QA', 'Qatar', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'RE', 'R√©union', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'RO', 'Romania', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'RU', 'Russian Federation', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'RW', 'Rwanda', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'BL', 'Saint Barth√©lemy', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SH', 'Saint Helena', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'KN', 'Saint Kitts and Nevis', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LC', 'Saint Lucia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'MF', 'Saint Martin (French part)', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'PM', 'Saint Pierre and Miquelon', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'VC', 'Saint Vincent', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'WS', 'Samoa', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SM', 'San Marino', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ST', 'Sao Tome and Principe', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SA', 'Saudi Arabia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SN', 'Senegal', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'RS', 'Serbia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SC', 'Seychelles', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SL', 'Sierra Leone', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SG', 'Singapore', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SX', 'Sint Maarten (Dutch part)', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SK', 'Slovakia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SI', 'Slovenia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SB', 'Solomon Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SO', 'Somalia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ZA', 'South Africa', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GS', 'South Georgia/Sandwich Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SS', 'South Sudan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ES', 'Spain', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'LK', 'Sri Lanka', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SD', 'Sudan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SR', 'Suriname', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SJ', 'Svalbard and Jan Mayen', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SZ', 'Swaziland', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SE', 'Sweden', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'CH', 'Switzerland', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'SY', 'Syrian Arab Republic', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TW', 'Taiwan, Province of China', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TJ', 'Tajikistan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TZ', 'Tanzania', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TH', 'Thailand', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TL', 'Timor-Leste', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TG', 'Togo', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TK', 'Tokelau', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TO', 'Tonga', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TT', 'Trinidad and Tobago', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TN', 'Tunisia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TR', 'Turkey', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TM', 'Turkmenistan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TC', 'Turks and Caicos Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'TV', 'Tuvalu', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'UG', 'Uganda', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'UA', 'Ukraine', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'AE', 'United Arab Emirates', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'GB', 'United Kingdom', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'US', 'United States', current_timestamp, current_timestamp, 2),"
                          + "       (DEFAULT, 'UM', 'US Minor Outlying Islands', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'UY', 'Uruguay', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'UZ', 'Uzbekistan', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'VU', 'Vanuatu', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'VE', 'Venezuela', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'VN', 'Viet Nam', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'VG', 'Virgin Islands, British', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'VI', 'Virgin Islands, U.S.', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'WF', 'Wallis and Futuna', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'EH', 'Western Sahara', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'YE', 'Yemen', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ZM', 'Zambia', current_timestamp, current_timestamp, 1),"
                          + "       (DEFAULT, 'ZW', 'Zimbabwe', current_timestamp, current_timestamp, 1)")

    ]
