# Generated by Django 2.2.2 on 2020-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingrate',
            name='code',
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='name',
            field=models.CharField(default='', max_length=63),
        ),
    ]
