# Generated by Django 2.2.2 on 2020-07-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20200723_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingcountry',
            old_name='zones',
            new_name='zone',
        ),
    ]
