# Generated by Django 2.2.2 on 2020-07-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_product', '0039_auto_20200723_1330'),
        ('shipping', '0003_auto_20200723_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingPriceAbstractVariant',
            new_name='ShippingCostAbstractVariant',
        ),
        migrations.AlterModelTable(
            name='shippingcostabstractvariant',
            table='shipping_cost_abstract_variant',
        ),
    ]
