# Generated by Django 2.2.2 on 2020-07-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20200723_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
