# Generated by Django 2.2.2 on 2020-08-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_shippingrate_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcostabstractvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_costs', to='abstract_product.AbstractProductVariant'),
        ),
    ]
