# Generated by Django 2.2.2 on 2020-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_auto_20200812_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcostabstractvariant',
            name='variant',
        ),
        migrations.AddField(
            model_name='shippingcostabstractvariant',
            name='abstract_variant_sku',
            field=models.CharField(default='', max_length=100),
        ),
    ]
