# Generated by Django 2.2.2 on 2020-09-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_auto_20200901_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcostabstractvariant',
            name='abstract_variant_sku',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
