# Generated by Django 2.2.2 on 2020-09-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_auto_20200901_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcountry',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
