# Generated by Django 2.2.2 on 2020-09-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_shippingcountry_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCity',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingCountry')),
            ],
            options={
                'db_table': 'shipping_city',
                'ordering': ['country', 'update_time', 'create_time'],
            },
        ),
    ]
