# Generated by Django 2.2.2 on 2020-09-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_shippingcity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingcity',
            options={'ordering': ['country', 'state', 'update_time', 'create_time']},
        ),
        migrations.CreateModel(
            name='ShippingState',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingCountry')),
            ],
            options={
                'db_table': 'shipping_state',
                'ordering': ['country', 'update_time', 'create_time'],
            },
        ),
        migrations.AddField(
            model_name='shippingcity',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingState'),
        ),
    ]
