# Generated by Django 2.2.2 on 2020-09-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_auto_20200921_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingstate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='shipping.ShippingCountry'),
        ),
    ]
