# Generated by Django 2.2.2 on 2020-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0012_auto_20200922_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcostabstractvariant',
            name='additional_cost',
        ),
        migrations.RemoveField(
            model_name='shippingcostabstractvariant',
            name='base_cost',
        ),
        migrations.RemoveField(
            model_name='shippingcostabstractvariant',
            name='fulfill_additional_cost',
        ),
        migrations.RemoveField(
            model_name='shippingcostabstractvariant',
            name='fulfill_base_cost',
        ),
        migrations.AddField(
            model_name='shippingcostabstractvariant',
            name='production_cost_additional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='shippingcostabstractvariant',
            name='production_cost_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='shippingcostabstractvariant',
            name='shipping_cost_additional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='shippingcostabstractvariant',
            name='shipping_cost_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
