# Generated by Django 2.2.2 on 2020-12-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_shopshippingprofile'),
        ('shipping', '0014_auto_20201028_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProfileDefault',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('profile_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipping_profile_default',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ShippingEcommerceDefaultZone',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('ecommerce', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.Ecommerce')),
                ('shipping_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='shipping.ShippingProfileDefault')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingZone')),
            ],
            options={
                'db_table': 'shipping_ecommerce_default_zone',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='ShippingEcommerceDefaultMethod',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('ecommerce_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='shipping.ShippingEcommerceDefaultZone')),
            ],
            options={
                'db_table': 'shipping_ecommerce_default_method',
                'ordering': ['create_time'],
            },
        ),
    ]
