# Generated by Django 2.2.2 on 2020-12-19 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0015_shippingecommercedefaultmethod_shippingecommercedefaultzone_shippingprofiledefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingecommercedefaultzone',
            name='ecommerce',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Ecommerce'),
        ),
    ]
