# Generated by Django 2.2.2 on 2020-12-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0016_auto_20201219_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingecommercedefaultzone',
            name='ecommerce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Ecommerce'),
        ),
    ]
