# Generated by Django 2.2.2 on 2020-12-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0017_auto_20201219_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingprofiledefault',
            name='profile_id',
        ),
    ]
