# Generated by Django 2.2.2 on 2020-12-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0018_remove_shippingprofiledefault_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingecommercedefaultzone',
            name='ecommerce',
        ),
        migrations.RemoveField(
            model_name='shippingecommercedefaultzone',
            name='shipping_profile',
        ),
        migrations.RemoveField(
            model_name='shippingecommercedefaultzone',
            name='zone',
        ),
        migrations.AlterField(
            model_name='shippingcountry',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='shipping.ShippingZone'),
        ),
        migrations.DeleteModel(
            name='ShippingEcommerceDefaultMethod',
        ),
        migrations.DeleteModel(
            name='ShippingEcommerceDefaultZone',
        ),
        migrations.DeleteModel(
            name='ShippingProfileDefault',
        ),
    ]
