# Generated by Django 2.2.2 on 2020-12-21 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shipping', '0019_auto_20201221_0510'),
    ]

    operations = [
        migrations.RunSQL("UPDATE public.shipping_country SET is_active = true WHERE is_active = false"),
    ]
