# Generated by Django 2.2.2 on 2019-10-05 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=512, unique=True)),
                ('card_name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=50)),
                ('last4', models.CharField(max_length=5)),
                ('exp_month', models.CharField(max_length=5)),
                ('exp_year', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=20)),
                ('billing_order', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stripe_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stripe',
                'verbose_name_plural': 'User Stripe',
                'db_table': 'billing_stripe_payment_method',
                'ordering': ['id'],
            },
        ),
    ]
