# Generated by Django 2.2.2 on 2019-10-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stripe_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstripe',
            name='fingerprint',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
