# Generated by Django 2.2.2 on 2019-10-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stripe_payment', '0002_userstripe_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstripe',
            name='fingerprint',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
