# Generated by Django 2.2.2 on 2019-10-19 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_payment', '0003_auto_20191019_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstripe',
            name='fingerprint',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='userstripe',
            unique_together={('user', 'fingerprint')},
        ),
    ]
