# Generated by Django 2.2.2 on 2019-10-19 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stripe_payment', '0004_auto_20191019_0942'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstripe',
            unique_together=set(),
        ),
    ]
