# Generated by Django 2.2.2 on 2019-10-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stripe_payment', '0005_auto_20191019_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstripe',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
