# Generated by Django 2.2.2 on 2019-10-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancelShippingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'approved'), ('2', 'rejected')], default='0', max_length=2)),
                ('approve_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_cancel_shipping_request',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField()),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('province_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=20, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_customer_info',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('total_item', models.IntegerField(default=0)),
                ('tags', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_pack_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mfr_pack_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fulfill_status', models.CharField(blank=True, choices=[('0', 'unfulfilled'), ('1', 'pending'), ('2', 'in_production'), ('3', 'fulfilled'), ('4', 'canceled'), ('5', 'canceled_shipping'), ('6', 'rejected')], default='0', max_length=50)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_company', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('currency', models.CharField(blank=True, default='USD', max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cancel_shipping_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_packs', to='order.CancelShippingRequest')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='order.Order')),
            ],
            options={
                'db_table': 'order_pack',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('quantity', models.BigIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('currency', models.CharField(max_length=30)),
                ('mfr_base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.Order')),
                ('order_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.OrderPack')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
