# Generated by Django 2.2.2 on 2019-10-05 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('user_product', '0001_initial'),
        ('order', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='user_product.UserVariant'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.CustomerInfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='cancelshippingrequest',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_cancel_shipping_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancelshippingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_shipping_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
