# Generated by Django 2.2.2 on 2019-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_auto_20191005_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.RunSQL(
            'UPDATE "order" SET code = 1920476157064370 + id;COMMIT;',
        ),
    ]
