# Generated by Django 2.2.2 on 2019-10-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0003_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.BigIntegerField(db_index=True, default=0, unique=True),
        ),
    ]
