# Generated by Django 2.2.2 on 2019-10-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0004_auto_20191009_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('province_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order_shipping_address',
            },
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='province',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='province_code',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='zip',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderShippingAddress'),
        ),
    ]
