# Generated by Django 2.2.2 on 2019-10-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0005_auto_20191011_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
