# Generated by Django 2.2.2 on 2019-10-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0006_auto_20191012_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpack',
            name='cancel_shipping_request',
        ),
        migrations.AddField(
            model_name='cancelshippingrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_shipping_requests', to='order.Order'),
        ),
        migrations.AddField(
            model_name='orderpack',
            name='cancel_shipping_requests',
            field=models.ManyToManyField(related_name='order_packs', to='order.CancelShippingRequest'),
        ),
    ]
