# Generated by Django 2.2.2 on 2019-10-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0007_auto_20191021_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpack',
            name='cancel_shipping_requests',
        ),
        migrations.AddField(
            model_name='cancelshippingrequest',
            name='order_packs',
            field=models.ManyToManyField(related_name='cancel_shipping_requests', to='order.OrderPack'),
        ),
    ]
