# Generated by Django 2.2.2 on 2019-10-24 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0009_auto_20191024_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
