# Generated by Django 2.2 on 2019-10-24 17:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0010_remove_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='order_tsv_met_5c11ea_gin'),
        ),
    ]
