# Generated by Django 2.2 on 2019-10-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0012_create_text_search_trigger_20191024_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
