# Generated by Django 2.2.2 on 2019-10-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0013_auto_20191024_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpack',
            name='tracking_url',
            field=models.URLField(blank=True, null=True, verbose_name='Tracking Url'),
        ),
    ]
