# Generated by Django 2.2.2 on 2019-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0014_orderpack_tracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpack',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
