# Generated by Django 2.2.2 on 2019-10-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0015_auto_20191026_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
