# Generated by Django 2.2 on 2019-11-05 15:10
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0017_update_order_number_in_text_search_20191031_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfill_status',
            field=models.CharField(blank=True, choices=[('5', 'unfulfilled'), ('6', 'pending'), ('3', 'in_production'),
                                                        ('4', 'partially_in_production'), ('1', 'fulfilled'),
                                                        ('2', 'partially_fulfilled'), ('7', 'canceled'),
                                                        ('8', 'canceled_shipping'), ('9', 'rejected')], default='5',
                                   max_length=50),
        ),
    ]
