# Generated by Django 2.2 on 2019-11-05 15:29
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0018_order_fulfill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='financial_status',
            field=models.CharField(blank=True, choices=[('1', 'pending'), ('3', 'paid'), ('2', 'partially_paid'),
                                                        ('4', 'canceled')], default='1', max_length=50),
        ),
    ]
