# Generated by Django 2.2 on 2019-11-05 15:29
from django.contrib.postgres.aggregates import ArrayAgg
from django.db import migrations

from order.services.order_status import update_order_static_financial_status, update_order_static_fulfill_status


def migrate_order_static_financial_status(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    orders = Order.objects.annotate(
        pack_financial_statuses=ArrayAgg('packs__invoice_pack__invoice__status', distinct=True))
    for order_obj in orders:
        update_order_static_financial_status(order_obj)


def migrate_order_static_fulfill_status(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    orders = Order.objects.annotate(pack_fulfill_statuses=ArrayAgg('packs__fulfill_status', distinct=True))
    for order_obj in orders:
        update_order_static_fulfill_status(order_obj)


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0019_order_financial_status'),
    ]

    operations = [
        migrations.RunPython(migrate_order_static_financial_status),
        migrations.RunPython(migrate_order_static_fulfill_status),
    ]
