# Generated by Django 2.2 on 2019-11-12 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0020_update_old_order_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-create_time']},
        ),
    ]
