# Generated by Django 2.2 on 2019-11-12 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0021_auto_20191107_1616'),
        ('order', '0021_auto_20191112_0349'),
    ]

    operations = [
    ]
