# Generated by Django 2.2 on 2019-11-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0022_merge_20191112_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_in_usd',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
