# Generated by Django 2.2 on 2019-11-12 08:18

from django.db import migrations

from system_metadata.services.currency_converter import convert_local_money_to_usd


def migrate_order_price_in_usd(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    for order_obj in Order.objects.all():
        total_price = order_obj.total_price
        total_price_in_usd = convert_local_money_to_usd(total_price, order_obj.currency)
        total_price_in_usd = round(total_price_in_usd, 5)
        previous_total_price = order_obj.total_price_in_usd
        if total_price_in_usd != previous_total_price:
            order_obj.total_price_in_usd = total_price_in_usd
        order_obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0023_order_total_price_in_usd'),
    ]

    operations = [
        migrations.RunPython(migrate_order_price_in_usd),
    ]
