# Generated by Django 2.2 on 2019-11-14 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0024_update_order_total_price_in_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershippingaddress',
            name='name',
        ),
    ]
