# Generated by Django 2.2 on 2019-11-14 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0025_remove_ordershippingaddress_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
    ]
