# Generated by Django 2.2 on 2019-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0026_auto_20191114_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
