# Generated by Django 2.2.2 on 2019-11-14 18:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system_metadata', '0004_auto_20191109_1112'),
        ('order', '0027_auto_20191114_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='e_commerce_shipping_lines',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_rate',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to='system_metadata.ShippingRate'),
        ),
    ]
