# Generated by Django 2.2 on 2019-11-19 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0028_auto_20191114_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('1', 'create_order'), ('2', 'update_order_fulfill_status'), ('3', 'update_order_financial_status'), ('4', 'sync_order_shipping_address'), ('5', 'update_order_item_variant'), ('6', 'update_order_item_quantity')], max_length=2)),
                ('message', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_histories', to='order.Order')),
            ],
            options={
                'db_table': 'order_history',
                'ordering': ['-id', '-order_id'],
            },
        ),
    ]
