# Generated by Django 2.2 on 2019-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0032_auto_20191125_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_editable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
