# Generated by Django 2.2.2 on 2019-12-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0033_order_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpack',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderpack',
            name='tracking_status',
            field=models.CharField(blank=True, choices=[('1', 'unknown'), ('2', 'pre_transit'), ('3', 'in_transit'), ('4', 'out_for_delivery'), ('5', 'delivered'), ('6', 'available_for_pickup'), ('7', 'return_to_sender'), ('8', 'failure'), ('9', 'cancelled'), ('10', 'error')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='financial_status',
            field=models.CharField(blank=True, choices=[('1', 'pending'), ('3', 'paid'), ('2', 'partially_paid'), ('4', 'canceled')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfill_status',
            field=models.CharField(blank=True, choices=[('5', 'unfulfilled'), ('6', 'pending'), ('3', 'in_production'), ('4', 'partially_in_production'), ('1', 'fulfilled'), ('2', 'partially_fulfilled'), ('7', 'canceled'), ('8', 'canceled_shipping'), ('9', 'rejected')], default='5', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderpack',
            name='fulfill_status',
            field=models.CharField(blank=True, choices=[('0', 'unfulfilled'), ('1', 'pending'), ('2', 'in_production'), ('3', 'fulfilled'), ('4', 'canceled'), ('5', 'canceled_shipping'), ('6', 'rejected')], default='0', max_length=2),
        ),
    ]
