# Generated by Django 2.2.2 on 2020-01-01 11:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import order.models.order


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0034_auto_20191231_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cached_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=order.models.order.cached_metadata),
        ),
    ]
