# Generated by Django 2.2 on 2019-11-12 08:18

from django.db import migrations

from order.models import Order
from order.services.order_status import update_order_tracking_status


def migrate_order_cached_metadata(apps, schema_editor):
    for order_obj in Order.objects.all():
        update_order_tracking_status(order_obj)


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0035_order_cached_metadata'),
    ]

    operations = [
        migrations.RunPython(migrate_order_cached_metadata),
    ]
