# Generated by Django 2.2 on 2020-01-03 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0036_update_order_cached_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_editable',
            new_name='is_item_editable',
        ),
    ]
