# Generated by Django 2.2.2 on 2020-01-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0037_auto_20200103_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='province_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
