# Generated by Django 2.2 on 2020-01-13 07:16

from django.db import migrations
from django.db.models import Count

from order.models import Order


def migrate_total_items(apps, schema_editor):
    for order_obj in Order.objects.annotate(item_count=Count("items", distinct=True)).all():
        order_obj.total_items = order_obj.item_count
        order_obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0039_auto_20200109_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_item',
            new_name='total_items',
        ),
        migrations.RunPython(migrate_total_items),
    ]
