# Generated by Django 2.2 on 2020-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0040_auto_20200113_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
