# Generated by Django 2.2 on 2020-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0041_auto_20200114_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_in_usd',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
