# Generated by Django 2.2.2 on 2020-02-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0045_auto_20200206_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_support_email_time',
            field=models.DateTimeField(null=True),
        ),
    ]
