# Generated by Django 2.2.2 on 2020-02-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0046_order_send_support_email_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='financial_status',
            field=models.CharField(blank=True, choices=[('1', 'pending'), ('3', 'paid'), ('2', 'partially_paid'), ('4', 'canceled'), ('5', 'failed')], default='1', max_length=2),
        ),
    ]
