# Generated by Django 2.2.2 on 2020-07-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0060_ecommerceunsyncedproduct_ecommerceunsyncvariant_uservariantartworkfusion'),
        ('order', '0048_auto_20200630_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ecommerce_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_variant', to='user_product.EcommerceUnsyncVariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mapping_status',
            field=models.CharField(blank=True, choices=[('0', 'notmap'), ('1', 'unmapped'), ('2', 'mapped')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='user_product.UserVariant'),
        ),
    ]
