# Generated by Django 2.2.2 on 2020-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_auto_20200707_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unresolved_support_ticket',
            field=models.SmallIntegerField(default=0),
        ),
    ]
