# Generated by Django 2.2.2 on 2020-07-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_order_unresolved_support_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='unresolved_support_ticket',
            new_name='support_ticket_count',
        ),
        migrations.AddField(
            model_name='order',
            name='unresolved_support_ticket_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
