# Generated by Django 2.2.2 on 2020-07-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_auto_20200709_0906'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_rate',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to='shipping.ShippingRate'),
        ),
    ]
