# Generated by Django 2.2.2 on 2020-07-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_auto_20200723_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpack',
            name='reject_reason_type',
            field=models.CharField(blank=True, choices=[('2', 'not_support_shipping'), ('3', 'fulfill_rejected')], default='1', max_length=2, null=True),
        ),
    ]
