# Generated by Django 2.2.2 on 2020-07-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_orderpack_reject_reason_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        )
    ]
