# Generated by Django 2.2.2 on 2020-07-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_auto_20200724_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpack',
            name='production_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
