# Generated by Django 2.2.2 on 2020-07-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0057_auto_20200724_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfill_status',
            field=models.CharField(blank=True, choices=[('5', 'unfulfilled'), ('6', 'pending'), ('3', 'in_production'), ('4', 'partially_in_production'), ('1', 'fulfilled'), ('2', 'partially_fulfilled'), ('7', 'canceled'), ('8', 'canceled_shipping'), ('9', 'rejected'), ('10', 'requested_fulfillment')], default='5', max_length=2),
        ),
    ]
