# Generated by Django 2.2.2 on 2020-07-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_auto_20200724_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfill_status',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=2),
        ),
    ]
