# Generated by Django 2.2.2 on 2020-07-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0060_orderitem_fulfill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_item_editable',
        ),
    ]
