# Generated by Django 2.2.2 on 2020-07-28 08:04

from django.db import migrations, models
import django.db.models.deletion


def migrate_order_pack_has_multiple_fulfillment_sub_packs(apps, schema_editor):
    OrderPack = apps.get_model("order", "OrderPack")
    FulfillmentOrderPack = apps.get_model("order", "FulfillmentOrderPack")

    for order_pack_obj in OrderPack.objects.exclude(mfr_pack_id=None):
        FulfillmentOrderPack.objects.create(order_pack=order_pack_obj, mfr_pack_id=order_pack_obj.mfr_pack_id,
                                            quantity=0,
                                            tracking_id=order_pack_obj.tracking_id,
                                            tracking_number=order_pack_obj.tracking_number,
                                            tracking_url=order_pack_obj.tracking_url,
                                            tracking_status=order_pack_obj.tracking_status)


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0061_remove_order_is_item_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentOrderPack',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('mfr_pack_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tracking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_company', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True, verbose_name='Tracking Url')),
                ('tracking_status', models.CharField(
                    choices=[('1', 'unknown'), ('2', 'pre_transit'), ('3', 'in_transit'), ('4', 'out_for_delivery'),
                             ('5', 'delivered'), ('6', 'available_for_pickup'), ('7', 'return_to_sender'),
                             ('8', 'failure'), ('9', 'cancelled'), ('10', 'error')], default='1', max_length=2)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order_pack',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_order_packs',
                                   to='order.OrderPack')),
            ],
            options={
                'db_table': 'order_fulfillment_pack',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(migrate_order_pack_has_multiple_fulfillment_sub_packs)
    ]
