# Generated by Django 2.2.2 on 2020-07-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_fulfillmentorderpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentorderpack',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
