# Generated by Django 2.2.2 on 2020-07-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0064_auto_20200728_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpack',
            name='tracking_company',
        ),
        migrations.RemoveField(
            model_name='orderpack',
            name='tracking_id',
        ),
        migrations.RemoveField(
            model_name='orderpack',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='orderpack',
            name='tracking_status',
        ),
        migrations.RemoveField(
            model_name='orderpack',
            name='tracking_url',
        ),
    ]
