# Generated by Django 2.2.2 on 2020-07-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0065_auto_20200728_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpack',
            name='mfr_pack_id',
        ),
    ]
