# Generated by Django 2.2.2 on 2020-07-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0066_remove_orderpack_mfr_pack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='fulfill_status',
            field=models.CharField(choices=[('1', 'accepted'), ('2', 'rejected')], default='1', max_length=2),
        ),
    ]
