# Generated by Django 2.2.2 on 2020-08-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0067_auto_20200731_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpack',
            options={'ordering': ['create_time']},
        ),
    ]
