# Generated by Django 2.2.2 on 2020-09-08 08:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200817_1000'),
        ('order', '0068_auto_20200806_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='OrderInvalid',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('reason_code', models.CharField(blank=True, choices=[('1', 'no_customer_info'), ('2', 'not_support_shipping'), ('3', 'fulfill_rejected')], max_length=2)),
                ('reason_description', models.TextField(blank=True, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invalid_order', to='order.Order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invalid_order', to='shop.Shop')),
            ],
            options={
                'db_table': 'order_invalid',
                'ordering': ['-id'],
            },
        ),
    ]
