# Generated by Django 2.2.2 on 2020-09-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_auto_20200910_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvalid',
            name='order_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
