# Generated by Django 2.2.2 on 2020-09-15 06:42

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_auto_20200910_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvalid',
            name='tsv_metadata_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='orderinvalid',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('1', 'no_customer_info'), ('2', 'no_shipping_address'), ('3', 'not_support_shipping'), ('4', 'fulfill_rejected'), ('5', 'item_not_in_printholo'), ('6', 'shop_invalid'), ('7', 'unpaid_order'), ('8', 'other')], max_length=2),
        ),
        migrations.AddIndex(
            model_name='orderinvalid',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='order_inval_tsv_met_fb897a_gin'),
        ),
    ]
