# Generated by Django 2.2.2 on 2020-09-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_auto_20200915_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentorderpack',
            name='mfr_pack_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
