# Generated by Django 2.2.2 on 2020-09-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0073_auto_20200917_0936'),
    ]

    migration = '''
        CREATE OR REPLACE  FUNCTION order_invalid_tsv_metadata_search_trigger() RETURNS trigger AS $$
        declare 
            shop_info text;
        begin
            SELECT CONCAT(name, ' ', url) into shop_info FROM shop WHERE id = new.shop_id;
            new.tsv_metadata_search := setweight(to_tsvector(coalesce(new.order_id,'')), 'A') || setweight(to_tsvector(coalesce(shop_info,'')), 'A');
        return new;
        end
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER order_invalid_tsv_metadata_search_update BEFORE INSERT OR UPDATE
        ON order_invalid FOR EACH ROW EXECUTE PROCEDURE order_invalid_tsv_metadata_search_trigger();

        -- Force triggers to run and populate the text_search column.
        UPDATE order_invalid set ID = ID;
    '''

    reverse_migration = '''
        DROP TRIGGER order_invalid_tsv_metadata_search_update ON order_invalid;
    '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
