# Generated by Django 2.2.2 on 2020-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0074_tsv_search_meta_data_order_invalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvalid',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('4', 'order_existed'), ('5', 'item_not_in_printholo'), ('6', 'shop_invalid'), ('7', 'unpaid_order'), ('8', 'other')], max_length=2),
        ),
    ]
