# Generated by Django 2.2.2 on 2020-09-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0075_auto_20200917_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CustomerInfo'),
        ),
    ]
