# Generated by Django 2.2.2 on 2020-09-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20200918_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershippingaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ordershippingaddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ordershippingaddress',
            name='province_code',
        ),
    ]
