# Generated by Django 2.2.2 on 2020-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_auto_20200918_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
