# Generated by Django 2.2.2 on 2020-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0078_orderhistory_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
