# Generated by Django 2.2.2 on 2020-09-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0079_auto_20200918_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('1', 'standard'), ('2', 'sample')], default='1', max_length=2),
        ),
    ]
