# Generated by Django 2.2.2 on 2020-09-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0081_auto_20200922_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
