# Generated by Django 2.2.2 on 2020-09-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0082_auto_20200922_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
