# Generated by Django 2.2.2 on 2020-09-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0083_auto_20200922_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
