# Generated by Django 2.2.2 on 2020-09-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0084_auto_20200923_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
    ]
