# Generated by Django 2.2.2 on 2020-10-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0085_auto_20200923_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpack',
            name='fulfill_status',
            field=models.CharField(blank=True, choices=[('0', 'unfulfilled'), ('1', 'pending'), ('2', 'in_production'), ('3', 'fulfilled'), ('4', 'canceled'), ('5', 'canceled_shipping'), ('6', 'rejected'), ('7', 'requested_fulfillment')], db_index=True, default='0', max_length=2),
        ),
    ]
