# Generated by Django 2.2.2 on 2020-10-23 07:57

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_auto_20201005_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHolding',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('fulfillment_payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('printholo_cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('fulfillment_cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tsv_metadata_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_holding', to='order.Order')),
            ],
            options={
                'db_table': 'order_holding',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='orderholding',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_metadata_search'], name='order_holdi_tsv_met_0a8744_gin'),
        ),
    ]
