# Generated by Django 2.2.2 on 2020-09-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0087_auto_20201023_0757'),
    ]

    migration = '''
        CREATE OR REPLACE  FUNCTION order_holding_tsv_metadata_search_trigger() RETURNS trigger AS $$
        begin
            new.tsv_metadata_search := setweight(to_tsvector(coalesce(new.order_id::text)), 'A') || setweight(to_tsvector(coalesce(new.id::text)), 'A');
        return new;
        end
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER order_holding_tsv_metadata_search_update BEFORE INSERT OR UPDATE
        ON order_holding FOR EACH ROW EXECUTE PROCEDURE order_holding_tsv_metadata_search_trigger();

        -- Force triggers to run and populate the text_search column.
        UPDATE order_holding set ID = ID;
    '''

    reverse_migration = '''
        DROP TRIGGER order_holding_tsv_metadata_search_update ON order_holding;
    '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
