# Generated by Django 2.2.2 on 2020-09-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0088_search_metadata_order_holding'),
    ]

    migration = '''
        DROP TRIGGER order_holding_tsv_metadata_search_update ON order_holding;
    '''

    reverse_migration = '''
        DROP TRIGGER order_holding_tsv_metadata_search_update ON order_holding;
    '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
