# Generated by Django 2.2.2 on 2020-10-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0089_drop_tsv_search_meta'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderholding',
            name='order_holdi_tsv_met_0a8744_gin',
        ),
        migrations.RemoveField(
            model_name='orderholding',
            name='tsv_metadata_search',
        ),
    ]
