# Generated by Django 2.2.2 on 2020-10-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0090_auto_20201023_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
