# Generated by Django 2.2.2 on 2020-11-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_orderitem_base_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extra_artwork_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
