# Generated by Django 2.2.2 on 2020-11-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0092_orderitem_extra_artwork_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='extra_artwork_cost',
            new_name='extra_cost',
        ),
    ]
