# Generated by Django 2.2.2 on 2020-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0093_auto_20201103_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpack',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
