# Generated by Django 2.2.2 on 2020-11-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0094_auto_20201120_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_discount',
            new_name='discount',
        ),
    ]
