# Generated by Django 2.2.2 on 2020-11-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_auto_20201120_1800'),
        ('order', '0094_auto_20201124_0409'),
    ]

    operations = [
    ]
