# Generated by Django 2.2.2 on 2020-12-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0096_merge_20201125_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='type',
            field=models.CharField(choices=[('1', 'create_order'), ('2', 'update_order_fulfill_status'), ('3', 'update_order_financial_status'), ('4', 'update_order_shipping_address'), ('7', 'update_order_shipping_rate'), ('5', 'update_order_item_variant'), ('6', 'update_order_item_quantity'), ('8', 'update_order_is_item_editable_status'), ('9', 'create_support_ticket'), ('10', 'update_support_ticket'), ('11', 'reject_item_by_fulfill'), ('12', 'reject_not_support_shipping_item'), ('13', 'reject_no_shipping_item'), ('14', 'reject_order_by_fulfill'), ('15', 'remove_order_item')], max_length=2),
        ),
    ]
