# Generated by Django 2.2.2 on 2020-12-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0099_sampleshippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_mfr_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
