# Generated by Django 2.2.2 on 2021-01-07 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0101_ordercomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomments',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordercomments',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.Order'),
        ),
    ]
