# Generated by Django 2.2.2 on 2021-01-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0103_auto_20210107_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmentorderpack',
            name='origin_tracking_url',
            field=models.URLField(blank=True, null=True, verbose_name='Origin Tracking Url'),
        ),
    ]
