# Generated by Django 2.2.2 on 2021-01-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0126_textpersonalization_userfontfamily'),
        ('order', '0104_fulfillmentorderpack_origin_tracking_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemTextPersonalization',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('personal_text', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_personalization_set', to='order.OrderItem')),
                ('text_personalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_product.TextPersonalization')),
            ],
            options={
                'db_table': 'order__order_item_text_personalization',
                'ordering': ['id'],
                'unique_together': {('order_item', 'text_personalization')},
            },
        ),
    ]
