# Generated by Django 2.2.2 on 2021-02-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0104_fulfillmentorderpack_origin_tracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvalid',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('4', 'order_existed'), ('5', 'item_not_in_printholo'), ('6', 'shop_invalid'), ('7', 'unpaid_order'), ('8', 'other'), ('9', 'partial_item_in_printholo')], max_length=2),
        ),
    ]
