# Generated by Django 2.2.2 on 2021-02-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0105_fulfillmentorderpack_manually_update'),
        ('order', '0105_auto_20210218_0936'),
    ]

    operations = [
    ]
