# Generated by Django 2.2.2 on 2021-03-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0106_merge_20210222_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfill_status',
            field=models.CharField(blank=True, choices=[('5', 'unfulfilled'), ('6', 'pending'), ('3', 'in_production'), ('4', 'partially_in_production'), ('1', 'fulfilled'), ('2', 'partially_fulfilled'), ('7', 'canceled'), ('8', 'canceled_shipping'), ('9', 'rejected'), ('10', 'requested_fulfillment'), ('11', 'holding')], default='5', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fulfill_status',
            field=models.CharField(choices=[('1', 'accepted'), ('2', 'rejected'), ('3', 'holding')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderpack',
            name='fulfill_status',
            field=models.CharField(blank=True, choices=[('0', 'unfulfilled'), ('1', 'pending'), ('2', 'in_production'), ('3', 'fulfilled'), ('4', 'canceled'), ('5', 'canceled_shipping'), ('6', 'rejected'), ('7', 'requested_fulfillment'), ('11', 'holding')], db_index=True, default='0', max_length=2),
        ),
    ]
