# Generated by Django 2.2.2 on 2021-03-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0106_merge_20210222_0645'),
        ('order', '0106_random_id_model'),
    ]

    operations = [
    ]
