# Generated by Django 2.2.2 on 2021-03-09 09:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0106_merge_20210222_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('tracking_code', models.CharField(db_index=True, max_length=255)),
                ('carrier', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'unknown'), ('2', 'pre_transit'), ('3', 'in_transit'), ('4', 'out_for_delivery'), ('5', 'delivered'), ('6', 'available_for_pickup'), ('7', 'return_to_sender'), ('8', 'failure'), ('9', 'cancelled'), ('10', 'error')], default='1', max_length=2)),
                ('histories', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('fulfillment_order_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='order.FulfillmentOrderPack')),
            ],
            options={
                'db_table': 'order_tracker',
                'ordering': ['-create_time'],
            },
        ),
    ]
