# Generated by Django 2.2.2 on 2021-03-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0107_ordertracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertracker',
            old_name='histories',
            new_name='payloads',
        ),
        migrations.RemoveField(
            model_name='ordertracker',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='ordertracker',
            name='status',
        ),
    ]
