# Generated by Django 2.2.2 on 2021-03-01 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0108_auto_20210305_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMappingSkuLog',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('ph_product_sku', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=1000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
