# Generated by Django 2.2.2 on 2021-03-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0109_ordermappingskulog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordermappingskulog',
            table='order_mapping_sku_log',
        ),
    ]
