# Generated by Django 2.2.2 on 2021-03-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0110_auto_20210301_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered_order',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_edit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
