# Generated by Django 2.2.2 on 2021-03-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0112_update_seller_edit_time_20210310_1058'),
        ('order', '0108_auto_20210309_1038'),
    ]

    operations = [
    ]
