# Generated by Django 2.2.2 on 2021-03-18 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0112_update_seller_edit_time_20210310_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='edit_order_items_delay',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AddField(
            model_name='order',
            name='request_order_processing_manually',
            field=models.BooleanField(default=False),
        ),
    ]
