# Generated by Django 2.2.2 on 2021-03-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0113_merge_20210315_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracker',
            name='fulfillment_order_pack',
        ),
    ]
