# Generated by Django 2.2.2 on 2021-03-10 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0113_auto_20210318_0421'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE public.order AS o SET edit_order_items_delay = (SELECT u.edit_order_items_delay FROM public.user_settings AS u WHERE user_id = (SELECT s.owner_id FROM public.shop AS s WHERE id = o.shop_id)) WHERE shop_id is not null AND (SELECT s.owner_id FROM public.shop AS s WHERE id = o.shop_id) is not null;"),
        migrations.RunSQL(
            "UPDATE public.order AS o SET request_order_processing_manually = (SELECT us.request_order_processing_manually FROM public.user_settings AS us WHERE user_id = (SELECT s.owner_id FROM public.shop AS s WHERE id = o.shop_id)) WHERE shop_id is not null AND (SELECT s.owner_id FROM public.shop AS s WHERE id = o.shop_id) is not null;")
    ]
