# Generated by Django 2.2.2 on 2021-03-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0114_remove_ordertracker_fulfillment_order_pack'),
        ('order', '0114_update_ffm_setting_by_order_20210318_1129'),
    ]

    operations = [
    ]
