# Generated by Django 2.2.2 on 2021-03-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0114_remove_ordertracker_fulfillment_order_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_send_mail_add_payment',
            field=models.BooleanField(default=False),
        ),
    ]
