# Generated by Django 2.2.2 on 2021-03-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0115_merge_20210318_0752'),
        ('order', '0115_order_is_send_mail_add_payment'),
    ]

    operations = [
    ]
