# Generated by Django 2.2.2 on 2021-03-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0107_merge_20210304_0946'),
        ('order', '0116_merge_20210318_0856'),
    ]

    operations = [
    ]
