# Generated by Django 2.2.2 on 2021-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0118_update_is_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_delivered_order',
            field=models.BooleanField(default=False),
        ),
    ]
